### ISSUE TITLE
about word covert to pdf failed

### ISSUE THREAD

**Issue by inspire90** [documents4j/documents4j#104]
13:41:40.269 [http-nio-8688-exec-5] INFO  o.d.d.local.Documents4jLocalServices [Documents4jLocalServices.java : 130] - documents4j: using default Word conversion script
13:41:40.444 [http-nio-8688-exec-5] INFO  c.d.c.msoffice.MicrosoftWordBridge [MicrosoftWordBridge.java : 47] - From-Microsoft-Word-Converter was started successfully
13:41:40.445 [http-nio-8688-exec-5] INFO  com.documents4j.job.LocalConverter [LocalConverter.java : 54] - The documents4j local converter has started successfully
13:41:40.447 [pool-2-thread-1] INFO  c.d.c.msoffice.MicrosoftWordBridge [AbstractMicrosoftOfficeBridge.java : 63] - Requested conversion from d:\file\uploadFiles\1600321299677dr6e8f11b18c3d45a184da228eb56095f8.docx (application/vnd.com.documents4j.any-msword) to C:\Windows\system32\config\systemprofile\temp_documents4j_local\92b22f04-f556-447b-843d-de684801fdb2\temp1 (application/pdf)
13:41:42.741 [http-nio-8688-exec-5] ERROR c.com.drail.tgproj.util.Word2PdfUtil [Word2PdfUtil.java : 119] - word×ª»»pdfÊ§°Ü
com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

The computer is installed with office2010 32-bit, the computer is win10 64-bit, but the other computer is 64-bit, and the 2016 office 64-bit installed, there is no error.

**Comment by raphw** [comment]
Seems like the converter cannot access the file system. Did you give it correct privileges?
