### ISSUE TITLE
Issue while converting specific doc file to pdf.

### ISSUE THREAD

**Issue by amarpawar** [documents4j/documents4j#125]
I am getting the following exception while converting the attached file with a remote converter.

```
2021-07-02 16:00:08,007 INFO  [pool-3-thread-3] c.d.w.e.AsynchronousConversionResponse - Sending exceptional response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@150b0630
com.documents4j.throwables.FileSystemInteractionException: Could not access target file
    at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
    at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
    at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
    at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
    at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
    at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
    at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

This is not related to the folder access issue as it is working properly for other files.
Following is the link to the file for which I am facing the issue.

https://github.com/amarpawar/DocFileForConversion/blob/main/file-sample_100kB.doc

Thanks in advance.

**Comment by raphw** [comment]
Does the Java process have access to the file system that you are using? Make sure this is possible from the user that is running the process.

**Comment by amarpawar** [comment]
The same code is working for other files. I  am facing the issue when processing this file only.

**Comment by raphw** [comment]
That sounds strange. Might this be linked to an access policy?
