### ISSUE TITLE
Error The input file seems to be corrupt

### ISSUE THREAD

**Issue by CIT00** [documents4j/documents4j#134]
error when convert docx to pdf 
this my code 

        IConverter converter = LocalConverter
        		.builder()
        		.baseFolder(new File(path))
        		.build();
 
        Future<Boolean> conversion = converter
                .convert(in).as( DocumentType.DOCX ) // MS_EXCEL , MS_WORD
                .to(bo).as( DocumentType.PDF )
                .prioritizeWith( 1000 ) // optional 
                .schedule();
        
        conversion.get();
        
        try (OutputStream outputStream = new FileOutputStream( createFolderName + "/reportCoverNote_PDF_" + pageNo + ".pdf")) {
            bo.writeTo(outputStream);
        } catch (IOException e) {
            e.printStackTrace();
        }

[3/11/22 15:42:27:950 ICT] 00001455 SystemOut     O 2022-03-11 15:42:27.950 DEBUG 19352 --- [ool-42-thread-1] org.zeroturnaround.exec.ProcessExecutor  : Started java.lang.ProcessImpl@f7bc03a5
[3/11/22 15:42:27:952 ICT] 00001455 SystemOut     O 2022-03-11 15:42:27.952 TRACE 19352 --- [ool-42-thread-1] c.d.j.LocalFutureWrappingPriorityFuture  : Context fetched for source D:\DataEntry\Fire\Covernote\Tmp\7c1eac8b-29f8-4138-9cf5-97e5c5f79145\temp1: com.documents4j.job.LocalConversionContext@93dc674e
[3/11/22 15:42:27:952 ICT] 00001455 SystemOut     O 2022-03-11 15:42:27.952 TRACE 19352 --- [ool-42-thread-1] c.d.j.LocalFutureWrappingPriorityFuture  : Underlying future created for source D:\DataEntry\Fire\Covernote\Tmp\7c1eac8b-29f8-4138-9cf5-97e5c5f79145\temp1: com.documents4j.conversion.ProcessFutureWrapper@dac26803
[3/11/22 15:42:27:952 ICT] 00001455 SystemOut     O 2022-03-11 15:42:27.952 TRACE 19352 --- [ool-42-thread-1] c.d.j.LocalFutureWrappingPriorityFuture  : Blocking during external conversion for source D:\DataEntry\Fire\Covernote\Tmp\7c1eac8b-29f8-4138-9cf5-97e5c5f79145\temp1: com.documents4j.conversion.ProcessFutureWrapper@dac26803
[3/11/22 15:42:27:952 ICT] 00001456 SystemOut     O 2022-03-11 15:42:27.952 TRACE 19352 --- [    Thread-3869] o.z.exec.stream.StreamPumper             : org.zeroturnaround.exec.stream.StreamPumper@afd2e332 started.
[3/11/22 15:42:27:953 ICT] 00001457 SystemOut     O 2022-03-11 15:42:27.953 TRACE 19352 --- [    Thread-3870] o.z.exec.stream.StreamPumper             : org.zeroturnaround.exec.stream.StreamPumper@858db8ed started.
[3/11/22 15:42:28:096 ICT] 00001457 SystemOut     O 2022-03-11 15:42:28.096 TRACE 19352 --- [    Thread-3870] o.z.exec.stream.StreamPumper             : org.zeroturnaround.exec.stream.StreamPumper@858db8ed finished.
[3/11/22 15:42:28:097 ICT] 00001456 SystemOut     O 2022-03-11 15:42:28.096 TRACE 19352 --- [    Thread-3869] o.z.exec.stream.StreamPumper             : org.zeroturnaround.exec.stream.StreamPumper@afd2e332 finished.
[3/11/22 15:42:28:100 ICT] 00001459 SystemOut     O 2022-03-11 15:42:28.099 DEBUG 19352 --- [ssImpl@f7bc03a5] org.zeroturnaround.exec.WaitForProcess   : java.lang.ProcessImpl@f7bc03a5 stopped with exit code -2
[3/11/22 15:42:28:100 ICT] 00001459 SystemOut     O 2022-03-11 15:42:28.100 TRACE 19352 --- [ssImpl@f7bc03a5] o.z.exec.stream.PumpStreamHandler        : Joining output thread Thread[Thread-3869,5,]...
[3/11/22 15:42:28:100 ICT] 00001459 SystemOut     O 2022-03-11 15:42:28.100 TRACE 19352 --- [ssImpl@f7bc03a5] o.z.exec.stream.PumpStreamHandler        : Joining error thread Thread[Thread-3870,5,]...
[3/11/22 15:42:28:100 ICT] 00001459 SystemOut     O 2022-03-11 15:42:28.100 TRACE 19352 --- [ssImpl@f7bc03a5] o.z.exec.stream.PumpStreamHandler        : Flushing output stream org.apache.commons.io.output.TeeOutputStream@1dce5ed4...
[3/11/22 15:42:28:100 ICT] 00001459 SystemOut     O 2022-03-11 15:42:28.100 TRACE 19352 --- [ssImpl@f7bc03a5] o.z.exec.stream.PumpStreamHandler        : Flushing error stream org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@fda0d10b...
[3/11/22 15:42:28:102 ICT] 00001455 SystemOut     O 2022-03-11 15:42:28.102 TRACE 19352 --- [ool-42-thread-1] c.d.j.LocalFutureWrappingPriorityFuture  : Conversion caused an error

java.util.concurrent.ExecutionException: The conversion finished unsuccessful
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:50) ~[documents4j-util-transformer-process-1.0.3.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36) ~[documents4j-util-transformer-process-1.0.3.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11) ~[documents4j-util-transformer-process-1.0.3.jar:na]
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78) ~[documents4j-util-conversion-1.0.3.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:1.8.0]
	at java.lang.Thread.run(Thread.java:822) [na:2.9 (11-02-2020)]
Caused by: com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159) ~[documents4j-util-all-1.0.3.jar:na]
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75) ~[documents4j-util-all-1.0.3.jar:na]
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70) ~[documents4j-transformer-api-1.0.3.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48) ~[documents4j-util-transformer-process-1.0.3.jar:na]
	... 6 common frames omitted

**Comment by raphw** [comment]
Have you tried converting the file using vbs scripts? Sometimes this yields the actual error message.

**Comment by CIT00** [comment]
when i start in develop machine it can convert. But in server can't convert and show this log

**Comment by raphw** [comment]
Have you ever opened Word on the server? Sometimes it gets stuck in some start dialogue.
