### ISSUE TITLE
Maven Tests fail during build

### ISSUE THREAD

**Issue by jposterloh** [documents4j/documents4j#140]
Hi, 

In preparation of working on Issue #126, I just checked out a fresh version of the code, to run 
`mvn package ms-office`

Unfortunately the build fails for me in the Microsoft Word tests (the conversions seem to be fine, however the shutdown seems broken:
 
```

Running com.documents4j.conversion.msoffice.MicrosoftWordConversionTest
Tests run: 3, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 2.036 sec <<< FAILURE! - in com.documents4j.conversion.msoffice.MicrosoftWordConversionTest
com.documents4j.conversion.msoffice.MicrosoftWordConversionTest  Time elapsed: 2.033 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected state: MS Office component is running expected:<-6> but was:<3>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at com.documents4j.conversion.msoffice.MicrosoftOfficeAssertionEngine.assertNotRunning(MicrosoftOfficeAssertionEngine.java:36)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeAssertingTest.setUp(AbstractMicrosoftOfficeAssertingTest.java:26)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBasedTest.setUp(AbstractMicrosoftOfficeBasedTest.java:37)
        at com.documents4j.conversion.msoffice.MicrosoftWordConversionTest.setUpConverter(MicrosoftWordConversionTest.java:48)

com.documents4j.conversion.msoffice.MicrosoftWordConversionTest  Time elapsed: 2.035 sec  <<< ERROR!
java.lang.NullPointerException: null
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBasedTest.tearDownConverter(AbstractMicrosoftOfficeBasedTest.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


```
And some more. Also they vary a little bit with each execution...
Any idea what's wrong? Seems to me more like a scheduling problem than a real fail...

Is there a possibility to skip certain tests, or to just execute specific tests of a module?

Best
Jan-Patrick

Here the surefire logs for complete stacks: 
[com.documents4j.conversion.msoffice.MicrosoftWordStartStopTest.txt](https://github.com/documents4j/documents4j/files/9757418/com.documents4j.conversion.msoffice.MicrosoftWordStartStopTest.txt)
[com.documents4j.conversion.msoffice.MicrosoftWordConversionTest.txt](https://github.com/documents4j/documents4j/files/9757419/com.documents4j.conversion.msoffice.MicrosoftWordConversionTest.txt)
[com.documents4j.conversion.msoffice.MicrosoftWordInaccessibilityTest.txt](https://github.com/documents4j/documents4j/files/9757420/com.documents4j.conversion.msoffice.MicrosoftWordInaccessibilityTest.txt)

**Comment by raphw** [comment]
It seems as if your Word installation might not behave as it is expected. Are you using a fresh installation of MS Office? Sometimes some dialogs pop up which are invisible to the script but trigger a different exit code. From the exception, it seems like Word is already running before the test is executed. It's important that you kill all Word processes before building. The test suite needs to be in control all Word related processes on the entire machine.

Currently, there is only the `ms-office` profile (I assume you are using `-Pms-office`). If it helps you, feel free to add several.

**Comment by jposterloh** [comment]
No, it's not a fresh installation. I made sure, that no Word is running before execution of the test via TaskManager. I then see that a headless Word instance is created that is using a lot of CPU during the tests, and I can observe in my temp folder a lot of word and pdf or other targets are created. Then Word exits, but the tests fails. Could be a different exit code, I'll try to debug that. 

Yes, I run -Pms-office. I found a way to execute the word/excel tests separately. I will now try debugging it...

**Comment by raphw** [comment]
Great. There's always a chance that different versions of word issue different behavior. A good way of debugging this layer is also to emulate the tests manually, by taking the files that the test issues, but then running the conversion in a console and executing the VBS scripts directly.
