### ISSUE TITLE
RemoteConverter does not work with the last version of SpringFramework

### ISSUE THREAD

**Issue by jromeort** [documents4j/documents4j#148]
Hi, I had an application running the LocalConverter to generate PDFs from Word files but I wanted to change it to use a RemoteConverter. With the local converter I didn't found any error, but when I switched to the remote converter I am not able to initialize it. If I create an application without SpringFramework everything works fine.

I generated a small application to test it:

OS: Windows 10
Java version: 17

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.6</version>
        <relativePath/>
    </parent>

    <groupId>org.example</groupId>
    <artifactId>Converter</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-client</artifactId>
            <version>1.1.10</version>
        </dependency>
    </dependencies>
</project>
```

I initialize the RemoteConverter with

```
Iconverter converter =  RemoteConverter.builder()
                .baseFolder(new File("C://tmp"))
                .workerPool(3, 10, 2, TimeUnit.SECONDS)
                .requestTimeout(20, TimeUnit.SECONDS)
                .baseUri("http://localhost:9998")
                .build();
```

Then when I run the application I have the following errors:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/ws/rs/core/Configuration
	at org.example.converter.main.Main.main(Main.java:16)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configuration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 1 more
````
and
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:116)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:123)
	at com.documents4j.job.RemoteConverter.makeConnectionManager(RemoteConverter.java:123)
	at com.documents4j.job.RemoteConverter.makeClient(RemoteConverter.java:100)
	at com.documents4j.job.RemoteConverter.<init>(RemoteConverter.java:57)
	at com.documents4j.job.RemoteConverter$Builder.build(RemoteConverter.java:290)
	at org.example.converter.main.Main.main(Main.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more
```

I tried to add the dependencies for `javax.ws.rs-api` and `commons-logging`, but then I have an error where it is not able to cast ClientBuilder as ClientBuilder:
```
Exception in thread "main" java.lang.LinkageError: ClassCastException: attempting to castjar:file:/C:/Users/jromeort/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/C:/Users/jromeort/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.jar!/javax/ws/rs/client/ClientBuilder.class
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:81)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:109)
	at com.documents4j.job.RemoteConverter.makeClient(RemoteConverter.java:110)
	at com.documents4j.job.RemoteConverter.<init>(RemoteConverter.java:57)
	at com.documents4j.job.RemoteConverter$Builder.build(RemoteConverter.java:290)
	at org.example.converter.main.Main.main(Main.java:21)
```

I haven't found any solution to this problem, but I receive similar errors if instead of using SpringFramework I import `jersey-media-jaxb` or `jakarta.ws.rs-api`

**Comment by raphw** [comment]
This is a classical dependency conflict. If you find the time, please update the versions used, test it and submit a PR. I can then release a new version.

**Comment by jromeort** [comment]
The RemoteConverter works properly with the last version of Springboot after merging https://github.com/documents4j/documents4j/pull/150

**Comment by dlonghit** [comment]
@raphw Any idea when that new version will release more or less?

**Comment by raphw** [comment]
I can do that now.

**Comment by raphw** [comment]
Published yesterday.

**Comment by dlonghit** [comment]
Thank you!
