### ISSUE TITLE
issues with creating the documents4j-master project in Eclipse

### ISSUE THREAD

**Issue by DevasishBanerjee** [documents4j/documents4j#157]
1.  Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @4e39d5f6 - Received this compile error in the pom.xml of documents4j-local-demo.
2. In documents4j-transformer-msoffice-excel corrupt.xml shows the error Multiple annotations found at this line:
	- Content is not allowed in 
	 prolog.

I am unable to create a maven clean install of the project. Please help.

**Comment by raphw** [comment]
Is there a stack trace to this?

**Comment by DevasishBanerjee** [comment]
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 23 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 23 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] [1m------------------------------------------------------------------------[m
[INFO] [1mReactor Build Order:[m
[INFO] 
[INFO] documents4j                                                        [pom]
[INFO] documents4j-api                                                    [jar]
[INFO] documents4j-util-all                                               [jar]
[INFO] documents4j-transformer-api                                        [jar]
[INFO] documents4j-transformer                                            [jar]
[INFO] documents4j-util-conversion                                        [jar]
[INFO] documents4j-test                                                   [jar]
[INFO] documents4j-local                                                  [jar]
[INFO] documents4j-util-transformer-process                               [jar]
[INFO] documents4j-transformer-msoffice                                   [pom]
[INFO] documents4j-transformer-msoffice-base                              [jar]
[INFO] documents4j-transformer-msoffice-test                              [jar]
[INFO] documents4j-transformer-msoffice-word                              [jar]
[INFO] documents4j-transformer-msoffice-excel                             [jar]
[INFO] documents4j-transformer-msoffice-powerpoint                        [jar]
[INFO] documents4j-local-demo                                             [war]
[INFO] documents4j-util-ws                                                [jar]
[INFO] documents4j-client                                                 [jar]
[INFO] documents4j-util-standalone                                        [jar]
[INFO] documents4j-client-standalone                                      [jar]
[INFO] documents4j-server                                                 [jar]
[INFO] documents4j-server-standalone                                      [jar]
[INFO] documents4j-aggregation                                            [jar]
[INFO] 
[INFO] [1m-----------------< [0;36mcom.documents4j:documents4j-parent[0;1m >-----------------[m
[INFO] [1mBuilding documents4j 1.1.9                                        [1/23][m
[INFO]   from pom.xml
[INFO] [1m--------------------------------[ pom ]---------------------------------[m
[INFO] 
[INFO] [1m--- [0;32mclean:3.2.0:clean[m [1m(default-clean)[m @ [36mdocuments4j-parent[0;1m ---[m
[INFO] 
[INFO] [1m--- [0;32mcheckstyle:2.15:check[m [1m(validate)[m @ [36mdocuments4j-parent[0;1m ---[m
[INFO] Starting audit...
Audit done.
[INFO] 
[INFO] [1m--- [0;32minstall:2.5.1:install[m [1m(default-install)[m @ [36mdocuments4j-parent[0;1m ---[m
[INFO] Installing E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\pom.xml to C:\Users\bdevasish\.m2\repository\com\documents4j\documents4j-parent\1.1.9\documents4j-parent-1.1.9.pom
[INFO] 
[INFO] [1m------------------< [0;36mcom.documents4j:documents4j-api[0;1m >-------------------[m
[INFO] [1mBuilding documents4j-api 1.1.9                                    [2/23][m
[INFO]   from documents4j-api\pom.xml
[INFO] [1m--------------------------------[ jar ]---------------------------------[m
[INFO] 
[INFO] [1m--- [0;32mclean:3.2.0:clean[m [1m(default-clean)[m @ [36mdocuments4j-api[0;1m ---[m
[INFO] Deleting E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\target
[INFO] 
[INFO] [1m--- [0;32mcheckstyle:2.15:check[m [1m(validate)[m @ [36mdocuments4j-api[0;1m ---[m
[INFO] Starting audit...
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\DocumentType.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IConversionJob.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithPriorityUnspecified.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithSourceSpecified.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithSourceUnspecified.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithTargetUnspecified.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IConverter.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IFileConsumer.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IFileSource.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IInputStreamConsumer.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\api\IInputStreamSource.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\throwables\ConversionFormatException.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\throwables\ConversionInputException.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\throwables\ConverterAccessException.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\throwables\ConverterException.java:0: File does not end with a newline.
E:\Remittance_App_14020222\documents4j-documents4j-1.1.9\documents4j-api\src\main\java\com\documents4j\throwables\FileSystemInteractionException.java:0: File does not end with a newline.
Audit done.
[INFO] [1m------------------------------------------------------------------------[m
[INFO] [1mReactor Summary for documents4j 1.1.9:[m
[INFO] 
[INFO] documents4j ........................................ [1;32mSUCCESS[m [  1.290 s]
[INFO] documents4j-api .................................... [1;31mFAILURE[m [  0.305 s]
[INFO] documents4j-util-all ............................... [1;33mSKIPPED[m
[INFO] documents4j-transformer-api ........................ [1;33mSKIPPED[m
[INFO] documents4j-transformer ............................ [1;33mSKIPPED[m
[INFO] documents4j-util-conversion ........................ [1;33mSKIPPED[m
[INFO] documents4j-test ................................... [1;33mSKIPPED[m
[INFO] documents4j-local .................................. [1;33mSKIPPED[m
[INFO] documents4j-util-transformer-process ............... [1;33mSKIPPED[m
[INFO] documents4j-transformer-msoffice ................... [1;33mSKIPPED[m
[INFO] documents4j-transformer-msoffice-base .............. [1;33mSKIPPED[m
[INFO] documents4j-transformer-msoffice-test .............. [1;33mSKIPPED[m
[INFO] documents4j-transformer-msoffice-word .............. [1;33mSKIPPED[m
[INFO] documents4j-transformer-msoffice-excel ............. [1;33mSKIPPED[m
[INFO] documents4j-transformer-msoffice-powerpoint ........ [1;33mSKIPPED[m
[INFO] documents4j-local-demo ............................. [1;33mSKIPPED[m
[INFO] documents4j-util-ws ................................ [1;33mSKIPPED[m
[INFO] documents4j-client ................................. [1;33mSKIPPED[m
[INFO] documents4j-util-standalone ........................ [1;33mSKIPPED[m
[INFO] documents4j-client-standalone ...................... [1;33mSKIPPED[m
[INFO] documents4j-server ................................. [1;33mSKIPPED[m
[INFO] documents4j-server-standalone ...................... [1;33mSKIPPED[m
[INFO] documents4j-aggregation ............................ [1;33mSKIPPED[m
[INFO] [1m------------------------------------------------------------------------[m
[INFO] [1;31mBUILD FAILURE[m
[INFO] [1m------------------------------------------------------------------------[m
[INFO] Total time:  2.401 s
[INFO] Finished at: 2023-07-13T15:48:27+05:30
[INFO] [1m------------------------------------------------------------------------[m
[ERROR] Failed to execute goal [32morg.apache.maven.plugins:maven-checkstyle-plugin:2.15:check[m [1m(validate)[m on project [36mdocuments4j-api[m: [1;31mFailed during checkstyle execution[m: There are 16 errors reported by Checkstyle 6.1.1 with checkstyle.xml ruleset. -> [1m[Help 1][m
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[ERROR] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   [1mmvn <args> -rf :documents4j-api[m

**Comment by raphw** [comment]
That's curious. I assume you have some global Maven settings configured.

**Comment by DevasishBanerjee** [comment]
Thanks for your reply. In course of new incidents, please note I could finally create the Maven build and installed the war in my Tomcat 9 server. Now the service starts without a problem. However, now I am getting the error the file seems to be corrupt. I have independently run the vbscript for creating the pdf file and it is working. I thought that the path that I am providing was incorrect and so I tried to check the path. The path to the file was correct, but it continued to give me the error. Till date I was not able to find ay solution.

**Comment by raphw** [comment]
Does the server process have rights to read the file?

**Comment by DevasishBanerjee** [comment]
How can I provide the rights? Should I run the Tomact service as LOCAL SERVICE or Administrator?

**Comment by DevasishBanerjee** [comment]
Here is the stack trace:-

com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:59)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:47)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:14)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by DevasishBanerjee** [comment]
Here are some other information:-

2023-07-19 13:57:22.466  INFO 8600 --- [nio-8080-exec-4] c.d.c.msoffice.MicrosoftWordBridge       : From-Microsoft-Word-Converter was started successfully
2023-07-19 13:57:22.466  INFO 8600 --- [nio-8080-exec-4] com.documents4j.job.LocalConverter       : The documents4j local converter has started successfully
2023-07-19 13:57:22.512  INFO 8600 --- [pool-3-thread-1] c.d.c.msoffice.MicrosoftWordBridge       : Requested conversion from D:\Tomcat9\temp\tmp5052878733940040209\a8049c97-4264-484e-b721-cb2c69c7dc8f\temp1 (application/vnd.openxmlformats-officedocument.wordprocessingml.document) to D:\Tomcat9\temp\tmp5052878733940040209\a8049c97-4264-484e-b721-cb2c69c7dc8f\temp2 (application/pdf)
2023-07-19 13:57:22.512  INFO 8600 --- [pool-3-thread-1] c.d.c.msoffice.MicrosoftWordBridge       : Running command for conversion '[cmd, /S, /C, ""D:\Tomcat9\temp\tmp5052878733940040209\word_convert369948885.vbs" "D:\Tomcat9\temp\tmp5052878733940040209\a8049c97-4264-484e-b721-cb2c69c7dc8f\temp1" "D:\Tomcat9\temp\tmp5052878733940040209\a8049c97-4264-484e-b721-cb2c69c7dc8f\temp2" "17""]'
