### ISSUE TITLE
documents4j-client conflict with RESTEasy

### ISSUE THREAD

**Issue by SilentGert** [documents4j/documents4j#160]
We are using `documents4j-client` to trigger Docx to PDF conversion on a remote machine. `documents4j-client` seems to depend on _Jersey_. We also use another dependency that requires _RESTEasy_. After an update both now implement the same JAX-RS API version. 

In our stack the _RESTEasy_ dependency got loaded first before _Jersey_. That led to the following exception:
```
Caused by: jakarta.ws.rs.ProcessingException: org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: org.glassfish.jersey.internal.inject.InjectionManager
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:652)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:424)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.lambda$executorSubmit$9(ClientInvocation.java:708)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at org.jboss.resteasy.concurrent.ContextualExecutors.lambda$runnable$2(ContextualExecutors.java:312)
	at datadog.trace.bootstrap.instrumentation.java.concurrent.Wrapper.run(Wrapper.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 common frames omitted
Caused by: org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: org.glassfish.jersey.internal.inject.InjectionManager
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:137)
	at jdk.proxy3/jdk.proxy3.$Proxy234.getAllInstances(Unknown Source)
	at org.glassfish.jersey.client.filter.EncodingFilter.getSupportedEncodings(EncodingFilter.java:90)
	at org.glassfish.jersey.client.filter.EncodingFilter.filter(EncodingFilter.java:64)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:644)
	... 8 common frames omitted
```

I assume that happened because `RemoteConverter` now instantiated a _RESTEasy_ client instead of a _Jersey_ client. I was only able to fix the issue in our stack by explicitly loading the _Jersey_ dependencies as the first dependency so the call to `ClientBuilder.newBuilder()` creates a `JerseyClientBuilder`.  

Before finding the solution I tried to understand if I can inject to `documents4j-client` which `ClientBuilder` implementation it should use and started to wonder:
- Does `documents4j-client` need to depend on _Jersey_ specific classes or could it also be compatible with RESTEasy?
- If it is tied to _Jersey_, should `RemoteConverter` rather use `JerseyClientBuilder` directly?

While creating the ticket here I stumbled upon this [file in META-INF](https://github.com/documents4j/documents4j/blob/master/documents4j-client/src/main/resources/META-INF/services/javax.ws.rs.client.ClientBuilder). The `javax.*` package is outdated and was replaced with `jakarta.*`. Would fixing the file name already fix the implemetation load issue?

**Comment by raphw** [comment]
It might just be possible to remove Jersey as a dependency. Would you want to give it a try as you already have a use case for it? I am happy to merge any improvements.

**Comment by SilentGert** [comment]
Yeah, we will have a look at it probably at the end of the week.
