### ISSUE TITLE
When i .execute() my converter i get : Could not access target file

### ISSUE THREAD

**Issue by KrimoZtn** [documents4j/documents4j#161]
**com.documents4j.throwables.FileSystemInteractionException: Could not access target file**
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by KrimoZtn** [comment]
could it be from the MS-word version ? idk

**Comment by raphw** [comment]
Did you set correct access rights? Maybe the target folder has not given write access?

**Comment by KrimoZtn** [comment]
hi , thanks for ur response, it worked after i installed a printer on this computer, it's weird
