### ISSUE TITLE
调用微软office2016时把ppt转换为pdf，报错No converter for conversion of application/vnd.com.documents4j.any-mspowerpoint to application/pdf available

### ISSUE THREAD

**Issue by simon-sun** [documents4j/documents4j#162]
maven依赖：
<dependency>
<groupId>com.documents4j</groupId>
   <artifactId>documents4j-local</artifactId>
   <version>1.1.12</version>
</dependency>
<dependency>
    <groupId>com.documents4j</groupId>
    <artifactId>documents4j-transformer-msoffice-powerpoint</artifactId>
    <version>1.1.12</version>
</dependency>
执行的代码：
import com.documents4j.api.DocumentType;
import com.documents4j.api.IConverter;
import com.documents4j.job.LocalConverter;
import java.io.*;
    public static void pptToPdf(String filePath, String outFilePath) {
        //源文件地址（格式：pptx文件）
        File inputPpt = new File(filePath);
        //导出文件地址（格式：pdf文件）
        File outputFile = new File(outFilePath);
        InputStream ppt = null;
        OutputStream outputStream = null;
        IConverter converter = null;
        try {
            ppt = new FileInputStream(inputPpt);
            outputStream = new FileOutputStream(outputFile);
            converter = LocalConverter.builder().build();
            converter.getSupportedConversions();
            //转换ppt=>pdf
            boolean flag = converter.convert(ppt).as(DocumentType.MS_POWERPOINT).to(outputStream).as(DocumentType.PDF).execute();
            if (flag) {System.out.println("文件名：" + outFilePath + " 转换成功！");}
        } catch (Exception e) {
            System.out.println("文件名：" + outFilePath + " 转换失败！");
            e.printStackTrace();
        } finally {
            try {
                if (ppt != null) {ppt.close();}
                if (outputStream != null) {outputStream.close();}
                if (converter != null) {converter.shutDown();}
            } catch (IOException e) {
                System.out.println("关闭流失败！");
                e.printStackTrace();
            }
        }
    }
使用main方法调用，输出错误：
关键错误信息：
No converter for conversion of application/vnd.com.documents4j.any-mspowerpoint to application/pdf available
输出全部错误信息：
10:17:35.638 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\simon\AppData\Local\Temp\tmp236754815851279601\word_start1877374516.vbs""] in C:\Users\simon\AppData\Local\Temp\tmp236754815851279601.
10:17:35.649 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Started java.lang.ProcessImpl@7d4793a8
10:17:37.680 [WaitForProcess-java.lang.ProcessImpl@7d4793a8] DEBUG org.zeroturnaround.exec.WaitForProcess - java.lang.ProcessImpl@7d4793a8 stopped with exit code 3
10:17:37.685 [main] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
10:17:37.688 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\simon\AppData\Local\Temp\tmp236754815851279601\excel_start1384676720.vbs""] in C:\Users\simon\AppData\Local\Temp\tmp236754815851279601.
10:17:37.691 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Started java.lang.ProcessImpl@387c703b
10:17:37.990 [WaitForProcess-java.lang.ProcessImpl@387c703b] DEBUG org.zeroturnaround.exec.WaitForProcess - java.lang.ProcessImpl@387c703b stopped with exit code 3
10:17:37.991 [main] INFO com.documents4j.conversion.msoffice.MicrosoftExcelBridge - From-Microsoft-Excel-Converter was started successfully
10:17:38.024 [main] INFO com.documents4j.job.LocalConverter - The documents4j local converter has started successfully
文件名：E:\items\develop\research\watermark\src-data\aaa-documents4j-pptx.pdf 转换失败！
10:17:38.041 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\simon\AppData\Local\Temp\tmp236754815851279601\word_shutdown397985458.vbs""] in C:\Users\simon\AppData\Local\Temp\tmp236754815851279601.
10:17:38.045 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Started java.lang.ProcessImpl@4e04a765
com.documents4j.throwables.ConversionInputException: No converter for conversion of application/vnd.com.documents4j.any-mspowerpoint to application/pdf available
	at com.documents4j.conversion.ConverterRegistry.lookup(ConverterRegistry.java:61)
	at com.documents4j.conversion.DefaultConversionManager.startConversion(DefaultConversionManager.java:30)
	at com.documents4j.job.LocalFutureWrappingPriorityFuture.startConversion(LocalFutureWrappingPriorityFuture.java:50)
	at com.documents4j.job.LocalFutureWrappingPriorityFuture.startConversion(LocalFutureWrappingPriorityFuture.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
10:17:38.148 [WaitForProcess-java.lang.ProcessImpl@4e04a765] DEBUG org.zeroturnaround.exec.WaitForProcess - java.lang.ProcessImpl@4e04a765 stopped with exit code 3
10:17:38.148 [main] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was shut down successfully
10:17:38.150 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\simon\AppData\Local\Temp\tmp236754815851279601\excel_shutdown1772055185.vbs""] in C:\Users\simon\AppData\Local\Temp\tmp236754815851279601.
10:17:38.153 [main] DEBUG org.zeroturnaround.exec.ProcessExecutor - Started java.lang.ProcessImpl@180bc464
10:17:38.335 [WaitForProcess-java.lang.ProcessImpl@180bc464] DEBUG org.zeroturnaround.exec.WaitForProcess - java.lang.ProcessImpl@180bc464 stopped with exit code 3
10:17:38.335 [main] INFO com.documents4j.conversion.msoffice.MicrosoftExcelBridge - From-Microsoft-Excel-Converter was shut down successfully
10:17:38.336 [main] INFO com.documents4j.job.LocalConverter - The documents4j local converter has shut down successfully

哪位大神能帮忙看下

**Comment by raphw** [comment]
Did you enable the power point converter?

**Comment by simon-sun** [comment]
不过，我发现一个BUG，怎么代码怎么给你那边
