### ISSUE TITLE
random ConverterAccessException: The converter could not process the request  error

### ISSUE THREAD

**Issue by shahtejas2009** [documents4j/documents4j#167]
Recently we updated to documents4j-server-standalone-1.1.9-shaded.jar.
We are hosting it on Window server 2019.
Suddenly we start getting error
Unhandled Exception Occured: com.documents4j.throwables.ConverterAccessException: The converter could not process the request
        at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117)
        at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
        at com.documents4j.ws.ConverterNetworkProtocol$Status.resolve(ConverterNetworkProtocol.java:98)
        at com.documents4j.job.WebserviceRequestFutureWrapper.handle(WebserviceRequestFutureWrapper.java:48)
        at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:38)
        at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:13)
        at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        
        
        If I restart the server, Same file is getting converted again.
        no further detail in error log

**Comment by raphw** [comment]
But this does not happen if you revert to the previous version?

**Comment by shahtejas2009** [comment]
As We are in production,  we can not revert until we know that reason is due to some specific version.
Previous version ran for like 1 year, we didn't face any issue.

**Comment by raphw** [comment]
I would not know that the version breaks. Otherwise This ticket would have more reports.
