### ISSUE TITLE
registerShutdownHook is security risks

### ISSUE THREAD

**Issue by mistaguy** [documents4j/documents4j#34]
I have deployed an application in the [Mendix ](http://mendix.com)but i cant do the conversion because of security permission. [Oracle ](http://docs.oracle.com/javase/7/docs/technotes/guides/security/permissions.html)also says it is risk to enable registration of hooks. 
So i am wondering if the registerShutdownHook is necessary, is there a way to avoid it.

`Aug  4 11:27:58.924 127.0.0.1 tr10000: ERROR - ActionManager: Exception in execution of monitored action '{"name":"Contract.EmailContract_IncludingMerge","type":"Microflow"}' (execution id: d91ec91b-c810-4422-af20-ad180afd4dea, execution type: CLIENT_ASYNC_MONITORED)
Aug  4 11:27:58.929 127.0.0.1 tr10000: ERROR - ActionManager: (1/96) com.mendix.modules.microflowengine.MicroflowException: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: java.lang.RuntimeException: Failed to convert documentsaccess denied ("java.lang.RuntimePermission" "shutdownHooks")
Aug  4 11:27:58.929 127.0.0.1 tr10000: ERROR - ActionManager: (2/96) 	at Contract.EmailContract_IncludingMerge (JavaAction : 'MergeToFileDocument')
Aug  4 11:27:58.929 127.0.0.1 tr10000: ERROR - ActionManager: (3/96) 
Aug  4 11:27:58.929 127.0.0.1 tr10000: ERROR - ActionManager: (4/96) Advanced stacktrace:
Aug  4 11:27:58.929 127.0.0.1 tr10000: ERROR - ActionManager: (5/96) 	at com.mendix.modules.microflowengine.MicroflowUtil.processException(MicroflowUtil.java:143)
Aug  4 11:27:58.929 127.0.0.1 tr10000: ERROR - ActionManager: (6/96) 
Aug  4 11:27:58.930 127.0.0.1 tr10000: ERROR - ActionManager: (7/96) Caused by: com.mendix.core.CoreException: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: java.lang.RuntimeException: Failed to convert documentsaccess denied ("java.lang.RuntimePermission" "shutdownHooks")
Aug  4 11:27:58.930 127.0.0.1 tr10000: ERROR - ActionManager: (8/96) 	at com.mendix.core.component.InternalCore.execute(InternalCore.java:394)
Aug  4 11:27:58.930 127.0.0.1 tr10000: ERROR - ActionManager: (9/96) 
Aug  4 11:27:58.930 127.0.0.1 tr10000: ERROR - ActionManager: (10/96) Caused by: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: java.lang.RuntimeException: Failed to convert documentsaccess denied ("java.lang.RuntimePermission" "shutdownHooks")
Aug  4 11:27:58.930 127.0.0.1 tr10000: ERROR - ActionManager: (11/96) 	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:198)
Aug  4 11:27:58.930 127.0.0.1 tr10000: ERROR - ActionManager: (12/96) 
Aug  4 11:27:58.931 127.0.0.1 tr10000: ERROR - ActionManager: (13/96) Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: java.lang.RuntimeException: Failed to convert documentsaccess denied ("java.lang.RuntimePermission" "shutdownHooks")
Aug  4 11:27:58.931 127.0.0.1 tr10000: ERROR - ActionManager: (14/96) 	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:36)
Aug  4 11:27:58.932 127.0.0.1 tr10000: ERROR - ActionManager: (15/96) 
Aug  4 11:27:58.932 127.0.0.1 tr10000: ERROR - ActionManager: (16/96) Caused by: java.lang.RuntimeException: Failed to convert documentsaccess denied ("java.lang.RuntimePermission" "shutdownHooks")
Aug  4 11:27:58.932 127.0.0.1 tr10000: ERROR - ActionManager: (17/96) 	at document4j.Document4j.Convert(Document4j.java:135)
Aug  4 11:27:58.933 127.0.0.1 tr10000: ERROR - ActionManager: (18/96) 	at pdfbox.actions.MergeToFileDocument.mergeFileDocuments(MergeToFileDocument.java:113)
Aug  4 11:27:58.933 127.0.0.1 tr10000: ERROR - ActionManager: (19/96) 	at pdfbox.actions.MergeToFileDocument.executeAction(MergeToFileDocument.java:76)
Aug  4 11:27:58.933 127.0.0.1 tr10000: ERROR - ActionManager: (20/96) 	at pdfbox.actions.MergeToFileDocument.executeAction(MergeToFileDocument.java:47)
Aug  4 11:27:58.933 127.0.0.1 tr10000: ERROR - ActionManager: (21/96) 	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
Aug  4 11:27:58.933 127.0.0.1 tr10000: ERROR - ActionManager: (22/96) 	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
Aug  4 11:27:58.933 127.0.0.1 tr10000: ERROR - ActionManager: (23/96) 	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
Aug  4 11:27:58.933 127.0.0.1 tr10000: ERROR - ActionManager: (24/96) 	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:188)
Aug  4 11:27:58.934 127.0.0.1 tr10000: ERROR - ActionManager: (25/96) 	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
Aug  4 11:27:58.934 127.0.0.1 tr10000: ERROR - ActionManager: (26/96) 	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:194)
Aug  4 11:27:58.934 127.0.0.1 tr10000: ERROR - ActionManager: (27/96) 	at com.mendix.core.component.InternalCore.execute(InternalCore.java:386)
Aug  4 11:27:58.934 127.0.0.1 tr10000: ERROR - ActionManager: (28/96) 	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:52)
Aug  4 11:27:58.934 127.0.0.1 tr10000: ERROR - ActionManager: (29/96) 	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
Aug  4 11:27:58.934 127.0.0.1 tr10000: ERROR - ActionManager: (30/96) 	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:192)
Aug  4 11:27:58.935 127.0.0.1 tr10000: ERROR - ActionManager: (31/96) 	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:149)
Aug  4 11:27:58.935 127.0.0.1 tr10000: ERROR - ActionManager: (32/96) 	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
Aug  4 11:27:58.935 127.0.0.1 tr10000: ERROR - ActionManager: (33/96) 	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
Aug  4 11:27:58.935 127.0.0.1 tr10000: ERROR - ActionManager: (34/96) 	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
Aug  4 11:27:58.935 127.0.0.1 tr10000: ERROR - ActionManager: (35/96) 	at com.mendix.core.actionmanagement.CustomActionMonitorImpl$$anonfun$run$1.apply(CustomMonitoredAction.scala:14)
Aug  4 11:27:58.935 127.0.0.1 tr10000: ERROR - ActionManager: (36/96) 	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:145)
Aug  4 11:27:58.935 127.0.0.1 tr10000: ERROR - ActionManager: (37/96) 	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
Aug  4 11:27:58.936 127.0.0.1 tr10000: ERROR - ActionManager: (38/96) 	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:147)
Aug  4 11:27:58.936 127.0.0.1 tr10000: ERROR - ActionManager: (39/96) 	at scala.util.Try$.apply(Try.scala:191)
Aug  4 11:27:58.936 127.0.0.1 tr10000: ERROR - ActionManager: (40/96) 	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:141)
Aug  4 11:27:58.936 127.0.0.1 tr10000: ERROR - ActionManager: (41/96) 	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
Aug  4 11:27:58.936 127.0.0.1 tr10000: ERROR - ActionManager: (42/96) 	at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:137)
Aug  4 11:27:58.936 127.0.0.1 tr10000: ERROR - ActionManager: (43/96) 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
Aug  4 11:27:58.936 127.0.0.1 tr10000: ERROR - ActionManager: (44/96) 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
Aug  4 11:27:58.937 127.0.0.1 tr10000: ERROR - ActionManager: (45/96) 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
Aug  4 11:27:58.937 127.0.0.1 tr10000: ERROR - ActionManager: (46/96) 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
Aug  4 11:27:58.937 127.0.0.1 tr10000: ERROR - ActionManager: (47/96) 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
Aug  4 11:27:58.937 127.0.0.1 tr10000: ERROR - ActionManager: (48/96) 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Aug  4 11:27:58.937 127.0.0.1 tr10000: ERROR - ActionManager: (49/96) 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Aug  4 11:27:58.937 127.0.0.1 tr10000: ERROR - ActionManager: (50/96) 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Aug  4 11:27:58.938 127.0.0.1 tr10000: ERROR - ActionManager: (51/96) 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Aug  4 11:27:58.938 127.0.0.1 tr10000: ERROR - ActionManager: (52/96) 
Aug  4 11:27:58.938 127.0.0.1 tr10000: ERROR - ActionManager: (53/96) Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "shutdownHooks")
Aug  4 11:27:58.938 127.0.0.1 tr10000: ERROR - ActionManager: (54/96) 	at java.security.AccessControlContext.checkPermission(Unknown Source)
Aug  4 11:27:58.938 127.0.0.1 tr10000: ERROR - ActionManager: (55/96) 	at java.security.AccessController.checkPermission(Unknown Source)
Aug  4 11:27:58.938 127.0.0.1 tr10000: ERROR - ActionManager: (56/96) 	at java.lang.SecurityManager.checkPermission(Unknown Source)
Aug  4 11:27:58.939 127.0.0.1 tr10000: ERROR - ActionManager: (57/96) 	at java.lang.Runtime.addShutdownHook(Unknown Source)
Aug  4 11:27:58.939 127.0.0.1 tr10000: ERROR - ActionManager: (58/96) 	at com.documents4j.job.ConverterAdapter.registerShutdownHook(ConverterAdapter.java:104)
Aug  4 11:27:58.939 127.0.0.1 tr10000: ERROR - ActionManager: (59/96) 	at com.documents4j.job.ConverterAdapter.<init>(ConverterAdapter.java:38)
Aug  4 11:27:58.939 127.0.0.1 tr10000: ERROR - ActionManager: (60/96) 	at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:46)
Aug  4 11:27:58.939 127.0.0.1 tr10000: ERROR - ActionManager: (61/96) 	at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:162)
Aug  4 11:27:58.940 127.0.0.1 tr10000: ERROR - ActionManager: (62/96) 	at document4j.Document4j.Convert(Document4j.java:41)
Aug  4 11:27:58.940 127.0.0.1 tr10000: ERROR - ActionManager: (63/96) 	at pdfbox.actions.MergeToFileDocument.mergeFileDocuments(MergeToFileDocument.java:113)
Aug  4 11:27:58.940 127.0.0.1 tr10000: ERROR - ActionManager: (64/96) 	at pdfbox.actions.MergeToFileDocument.executeAction(MergeToFileDocument.java:76)
Aug  4 11:27:58.940 127.0.0.1 tr10000: ERROR - ActionManager: (65/96) 	at pdfbox.actions.MergeToFileDocument.executeAction(MergeToFileDocument.java:47)
Aug  4 11:27:58.940 127.0.0.1 tr10000: ERROR - ActionManager: (66/96) 	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
Aug  4 11:27:58.940 127.0.0.1 tr10000: ERROR - ActionManager: (67/96) 	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
Aug  4 11:27:58.941 127.0.0.1 tr10000: ERROR - ActionManager: (68/96) 	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
Aug  4 11:27:58.941 127.0.0.1 tr10000: ERROR - ActionManager: (69/96) 	at com.mendix.core.actionmanagement.ActionManager$1.execute(ActionManager.java:188)
Aug  4 11:27:58.941 127.0.0.1 tr10000: ERROR - ActionManager: (70/96) 	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
Aug  4 11:27:58.941 127.0.0.1 tr10000: ERROR - ActionManager: (71/96) 	at com.mendix.core.actionmanagement.ActionManager.executeSync(ActionManager.java:194)
Aug  4 11:27:58.941 127.0.0.1 tr10000: ERROR - ActionManager: (72/96) 	at com.mendix.core.component.InternalCore.execute(InternalCore.java:386)
Aug  4 11:27:58.941 127.0.0.1 tr10000: ERROR - ActionManager: (73/96) 	at com.mendix.modules.microflowengine.actions.actioncall.JavaAction.execute(JavaAction.scala:52)
Aug  4 11:27:58.941 127.0.0.1 tr10000: ERROR - ActionManager: (74/96) 	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
Aug  4 11:27:58.942 127.0.0.1 tr10000: ERROR - ActionManager: (75/96) 	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:192)
Aug  4 11:27:58.942 127.0.0.1 tr10000: ERROR - ActionManager: (76/96) 	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:149)
Aug  4 11:27:58.942 127.0.0.1 tr10000: ERROR - ActionManager: (77/96) 	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:49)
Aug  4 11:27:58.942 127.0.0.1 tr10000: ERROR - ActionManager: (78/96) 	at com.mendix.core.actionmanagement.CoreAction.doCall(CoreAction.java:260)
Aug  4 11:27:58.942 127.0.0.1 tr10000: ERROR - ActionManager: (79/96) 	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:248)
Aug  4 11:27:58.942 127.0.0.1 tr10000: ERROR - ActionManager: (80/96) 	at com.mendix.core.actionmanagement.CustomActionMonitorImpl$$anonfun$run$1.apply(CustomMonitoredAction.scala:14)
Aug  4 11:27:58.942 127.0.0.1 tr10000: ERROR - ActionManager: (81/96) 	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2$$anon$1.execute(ActionDispatching.scala:145)
Aug  4 11:27:58.943 127.0.0.1 tr10000: ERROR - ActionManager: (82/96) 	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
Aug  4 11:27:58.943 127.0.0.1 tr10000: ERROR - ActionManager: (83/96) 	at com.mendix.core.session.Worker$$anonfun$receive$3$$anonfun$2.apply(ActionDispatching.scala:147)
Aug  4 11:27:58.943 127.0.0.1 tr10000: ERROR - ActionManager: (84/96) 	at scala.util.Try$.apply(Try.scala:191)
Aug  4 11:27:58.943 127.0.0.1 tr10000: ERROR - ActionManager: (85/96) 	at com.mendix.core.session.Worker$$anonfun$receive$3.applyOrElse(ActionDispatching.scala:141)
Aug  4 11:27:58.943 127.0.0.1 tr10000: ERROR - ActionManager: (86/96) 	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
Aug  4 11:27:58.943 127.0.0.1 tr10000: ERROR - ActionManager: (87/96) 	at com.mendix.core.session.Worker.aroundReceive(ActionDispatching.scala:137)
Aug  4 11:27:58.944 127.0.0.1 tr10000: ERROR - ActionManager: (88/96) 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
Aug  4 11:27:58.944 127.0.0.1 tr10000: ERROR - ActionManager: (89/96) 	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
Aug  4 11:27:58.944 127.0.0.1 tr10000: ERROR - ActionManager: (90/96) 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
Aug  4 11:27:58.944 127.0.0.1 tr10000: ERROR - ActionManager: (91/96) 	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
Aug  4 11:27:58.944 127.0.0.1 tr10000: ERROR - ActionManager: (92/96) 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
Aug  4 11:27:58.944 127.0.0.1 tr10000: ERROR - ActionManager: (93/96) 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Aug  4 11:27:58.945 127.0.0.1 tr10000: ERROR - ActionManager: (94/96) 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Aug  4 11:27:58.945 127.0.0.1 tr10000: ERROR - ActionManager: (95/96) 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Aug  4 11:27:58.945 127.0.0.1 tr10000: ERROR - ActionManager: (96/96) 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Aug  4 11:27:59.138 127.0.0.1 tr10000: ERROR - Connector: An error has occurred while handling the request. [User 'rvolz' with session id 'fe6281a5-a8d3-4962-bff3-5d673eccbb56' and roles 'CrestaEmployee']
Aug  4 11:27:59.138 127.0.0.1 tr10000: ERROR - Connector: (1/124) java.util.concurrent.ExecutionException: com.mendix.modules.microflowengine.MicroflowException: com.mendix.core.CoreRuntimeException: com.mendix.systemwideinterfaces.MendixRuntimeException: java.lang.RuntimeException: Failed to convert documentsaccess denied ("java.lang.RuntimePermission" "shutdownHooks")`

**Comment by raphw** [comment]
I can add aproperty to avoid it. Generally, the hook makes sure that the process does nor run when the vm shuts down. You should be able to enable the permission with a policy file.

**Comment by mistaguy** [comment]
Yes i can do that but my worry is the security as mentioned by Oracle

**Comment by raphw** [comment]
The reason this operation is considered unsecure is that a shutdownhook can theoretically prevent the application from shutting down. Therefore, you need to check the code in question and grant the privilege. This is perfectly save in the case of documents4j.
