### ISSUE TITLE
java.lang.IllegalStateException: class com.documents4j.conversion.msoffice.MicrosoftExcelBridge could not be created by a (File, long, TimeUnit) constructor

### ISSUE THREAD

**Issue by narbigcito** [documents4j/documents4j#41]
I'm trying to run the api to convert an excel to pdf on a computer with ios, but I get the following error

```
CrearPdf(lineas.fedex.service.procesoArchivo.ordenPago.OrdenPago)  Time elapsed: 1.45 sec  <<< ERROR!
java.lang.IllegalStateException: class com.documents4j.conversion.msoffice.MicrosoftExcelBridge could not be created by a (File, long, TimeUnit) constructor
	at org.zeroturnaround.exec.ProcessExecutor.redirectOutput(ProcessExecutor.java:479)
	at org.zeroturnaround.exec.ProcessExecutor.<init>(ProcessExecutor.java:154)
	at com.documents4j.conversion.AbstractExternalConverter.makePresetProcessExecutor(AbstractExternalConverter.java:54)
	at com.documents4j.conversion.AbstractExternalConverter.runNoArgumentScript(AbstractExternalConverter.java:70)
	at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.runNoArgumentScript(AbstractMicrosoftOfficeBridge.java:51)
	at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.tryStart(AbstractMicrosoftOfficeBridge.java:34)
	at com.documents4j.conversion.msoffice.MicrosoftExcelBridge.startUp(MicrosoftExcelBridge.java:48)
	at com.documents4j.conversion.msoffice.MicrosoftExcelBridge.<init>(MicrosoftExcelBridge.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:30)
	at com.documents4j.conversion.ExternalConverterDiscovery.makeAll(ExternalConverterDiscovery.java:42)
	at com.documents4j.conversion.ExternalConverterDiscovery.loadConfiguration(ExternalConverterDiscovery.java:85)
	at com.documents4j.conversion.DefaultConversionManager.<init>(DefaultConversionManager.java:22)
	at com.documents4j.job.LocalConverter.makeConversionManager(LocalConverter.java:79)
	at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:51)
	at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:186)
	at app.lineas.fedex.service.ordenPago.IGenerarOrdenPagoPdfFedex.generarOrdenDePagoCOnDocument4(IGenerarOrdenPagoPdfFedex.java:158)
	at lineas.fedex.service.procesoArchivo.ordenPago.OrdenPago.CrearPdf(OrdenPago.java:40)
```

This is my code:

```
public void generarOrdenDePagoCOnDocument4() {
        File excel = new File("src/main/java/app/lineas/fedex/service/ordenPago/files/ordenPagoLimpia.xls");
        File target = new File("src/main/java/app/lineas/fedex/service/ordenPago/files/out.pdf");
        IConverter converter = LocalConverter.builder()
                .baseFolder(new File("src/main/java/app/lineas/fedex/service/ordenPago/files/tmp"))
                .workerPool(20, 25, 2, TimeUnit.SECONDS)
                .processTimeout(5, TimeUnit.SECONDS)
                .build();

        Future<Boolean> conversion = converter
                .convert(excel).as(DocumentType.XLS)
                .to(target).as(DocumentType.PDF)
                .prioritizeWith(1000) // optional
                .schedule();

    }
```

This are my dependencies:

` <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-api</artifactId>
            <version>1.0.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-local</artifactId>
            <version>1.0.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-util-standalone</artifactId>
            <version>1.0.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-transformer-msoffice-excel</artifactId>
            <version>1.0.3</version>
        </dependency>
        
        <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-util-all</artifactId>
            <version>1.0.3</version>
        </dependency>     

        <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-util-conversion</artifactId>
            <version>1.0.3</version>
        </dependency>

        <dependency>
            <groupId>com.documents4j</groupId>
            <artifactId>documents4j-transformer</artifactId>
            <version>1.0.3</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>

        
        <dependency>
            <groupId>org.zeroturnaround</groupId>
            <artifactId>zt-exec</artifactId>
            <version>1.9</version>
        </dependency>`

**Comment by raphw** [comment]
Do you have MS Excel correctly installed on your current machine? Did you check the priviledges for executing it?

**Comment by narbigcito** [comment]
I don't have it, I use linux :/

**Comment by raphw** [comment]
documents4j uses native converters to get the conversion right. You need at leadt a windows server (remote API) and an office installation.
