### ISSUE TITLE
Remote conversion problem

### ISSUE THREAD

**Issue by marekzzz** [documents4j/documents4j#46]
Hi
Local conversion work perfectly.
But remote mode failed in my case.
My OS: Windows 8.1 + eclipse

What I did:
Server:
Inside documents4j-server-standalone-1.0.3-shaded.jar I add Class-Path: org.osgi.core-6.0.0.jar into MANIFEST.MF (there was a problem during server start).

Client:
I use version 1.0.3 of documents4j by there was jar chaos inside dependencies. 
So I was forced to add additional dependency:
<dependency>
    <groupId>org.glassfish.jersey.connectors</groupId>
    <artifactId>jersey-apache-connector</artifactId>
    <version>2.25.1</version>
</dependency>
to equall version on all jersey jars.

Finally server is runing and junit is runing. But I get an error on client side (junit):
java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:205)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
	at pl.gb.server.jobs.utils.WordConvertToPDF.convertToPdf(WordConvertToPDF.java:104)
	at pl.gb.server.jobs.utils.WordConvertToPDFTest.convertDocuments4j(WordConvertToPDFTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javax.ws.rs.ProcessingException: Error closing message content input stream.
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:161)
	at com.google.common.io.Closeables.close(Closeables.java:79)
	at com.documents4j.job.FileConsumerToInputStreamConsumer.onComplete(FileConsumerToInputStreamConsumer.java:34)
	at com.documents4j.job.RemoteFutureWrappingPriorityFuture.onConversionFinished(RemoteFutureWrappingPriorityFuture.java:69)
	at com.documents4j.job.RemoteFutureWrappingPriorityFuture.onConversionFinished(RemoteFutureWrappingPriorityFuture.java:15)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:253)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:213)
	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:315)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:143)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:227)
	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:136)
	at org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:94)
	at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$3.close(ApacheConnector.java:644)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:621)
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:158)
	... 8 more
2017-09-13 10:42:56.278 ERROR 9920 --- [           main] p.gb.server.jobs.utils.WordConvertToPDF  : convertToPdf(converter=com.documents4j.job.RemoteConverter@5df3f854, srcPath=c:\mnt\jobs\temp_files\1.docx, dstPath=c:\mnt\jobs\temp_files\WordConvertToPDFSufix\1.pdf) Could not complete conversion

java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:205)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
	at pl.gb.server.jobs.utils.WordConvertToPDF.convertToPdf(WordConvertToPDF.java:104)
	at pl.gb.server.jobs.utils.WordConvertToPDFTest.convertDocuments4j(WordConvertToPDFTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javax.ws.rs.ProcessingException: Error closing message content input stream.
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:161)
	at com.google.common.io.Closeables.close(Closeables.java:79)
	at com.documents4j.job.FileConsumerToInputStreamConsumer.onComplete(FileConsumerToInputStreamConsumer.java:34)
	at com.documents4j.job.RemoteFutureWrappingPriorityFuture.onConversionFinished(RemoteFutureWrappingPriorityFuture.java:69)
	at com.documents4j.job.RemoteFutureWrappingPriorityFuture.onConversionFinished(RemoteFutureWrappingPriorityFuture.java:15)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.MalformedChunkCodingException: CRLF expected at end of chunk
	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:253)
	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:213)
	at org.apache.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:315)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:143)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:172)
	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:227)
	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:136)
	at org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:94)
	at java.io.BufferedInputStream.close(BufferedInputStream.java:483)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$3.close(ApacheConnector.java:644)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at org.glassfish.jersey.apache.connector.ApacheConnector$HttpClientResponseInputStream.close(ApacheConnector.java:621)
	at org.glassfish.jersey.message.internal.EntityInputStream.close(EntityInputStream.java:158)
	... 8 common frames omitted

On server side is an error:
2017-09-13 10:42:56,260 DEBUG [Grizzly(5) SelectorRunner] o.g.grizzly.nio.transport.TCPNIOTransport - TCPNIOConnection (TCPNIOConnection{localSocketAddress={/127.0.0.1:9998}, peerSocketAddress={/127.0.0.1:63768}}) (allocated) read -1 bytes
2017-09-13 10:42:56,262 DEBUG [Grizzly(5) SelectorRunner] o.g.grizzly.filterchain.DefaultFilterChain - Exception during FilterChain execution
java.io.EOFException: null
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.read(TCPNIOTransport.java:648) [documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransportFilter.handleRead(TCPNIOTransportFilter.java:75) ~[documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.filterchain.TransportFilter.handleRead(TransportFilter.java:173) ~[documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) ~[documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:288) [documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:206) [documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:136) [documents4j-server-standalone-1.0.3-sh
aded2.jar:na]
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:114) [documents4j-server-standalone-1.0.3-sh
aded2.jar:na]
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) [documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:547) [documents4j-server-standalone-1.0.3-sh
aded2.jar:na]
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113) [documents4j-server-standalone-1.0.3
-shaded2.jar:na]
        at org.glassfish.grizzly.strategies.SameThreadIOStrategy.executeIoEvent(SameThreadIOStrategy.java:103) [documents4j-server-standalon
e-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:89) [documents4j-server-standalone-1.0
.3-shaded2.jar:na]
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:406) [documents4j-server-standalone-1.0.3-shaded2.j
ar:na]
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:375) [documents4j-server-standalone-1.0.3-shaded2.jar:na
]
        at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:339) [documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:271) [documents4j-server-standalone-1.0.3-shaded2.jar:na]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565) [documents4j-server-standalone-1.0
.3-shaded2.jar:na]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545) [documents4j-server-standalone-1.0.3-
shaded2.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_74]

Please help....

**Comment by raphw** [comment]
This looks a bit like this problem: https://blog.codecentric.de/2008/07/seiteneffekte-beim-connection-sharing/

**Comment by jagriti22** [comment]
Hi @raphw 

I am also facing same type of problem while converting docx into pdf.Please help me to resolve this issue.I would be grateful to you.

Thanks.

1107 [main] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
1156 [main] INFO com.documents4j.job.LocalConverter - The documents4j local converter has started successfully
1268 [pool-1-thread-1] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - Requested conversion from C:\Users\hp\Downloads\0ca6354b-a78f-4355-b99f-a0239b3770a5\temp1 (application/vnd.openxmlformats-officedocument.wordprocessingml.document) to C:\Users\hp\Downloads\0ca6354b-a78f-4355-b99f-a0239b3770a5\temp2 (application/pdf)
Exception in thread "main" java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:205)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
	at DocConv.DocxToPdf.main(DocxToPdf.java:43)
Caused by: com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
