### ISSUE TITLE
Remote conversion Problem

### ISSUE THREAD

**Issue by ikeachen01** [documents4j/documents4j#48]
Hi !
I set a server by documents4j-server-standalone-1.0.3-shaded.jar to convert the word files to the pdf files.
When the server occurs an exception, the following conversions will all fail.
Is this situation is right?
Can the server convert the following conversions after a exception occurs?

**Comment by ikeachen01** [comment]
the error message .....

2017-12-19 10:40:39,145 INFO  [Grizzly-worker(2)] c.d.w.e.AsynchronousConversionResponse - Registered conversion request for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@1d0ef058
2017-12-19 10:40:39,145 INFO  [pool-2-thread-1] c.d.c.msoffice.MicrosoftWordBridge - Requested conversion from C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1983 (application/vnd.com.documents4j.any-msword) to C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1984 (application/pdf)
2017-12-19 10:40:39,644 INFO  [pool-2-thread-1] c.d.w.e.AsynchronousConversionResponse - Sending successful response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@1d0ef058
2017-12-19 10:40:45,510 INFO  [Grizzly-worker(2)] c.d.w.e.AsynchronousConversionResponse - Registered conversion request for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@6e7cb364
2017-12-19 10:40:45,572 INFO  [pool-2-thread-2] c.d.c.msoffice.MicrosoftWordBridge - Requested conversion from C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1985 (application/vnd.com.documents4j.any-msword) to C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1986 (application/pdf)
2017-12-19 10:42:28,065 INFO  [Grizzly-worker(2)] c.d.w.e.AsynchronousConversionResponse - Registered conversion request for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@1712035e
2017-12-19 10:42:28,065 INFO  [pool-2-thread-5] c.d.c.msoffice.MicrosoftWordBridge - Requested conversion from C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1987 (application/vnd.com.documents4j.any-msword) to C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1988 (application/pdf)
2017-12-19 10:42:45,880 WARN  [HttpServer-0] c.d.w.e.AsynchronousConversionResponse - Conversion request timed out for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@6e7cb364
2017-12-19 10:42:45,880 INFO  [HttpServer-0] c.d.w.e.AsynchronousConversionResponse - Sending cancellation response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@6e7cb364
2017-12-19 10:42:48,377 WARN  [pool-2-thread-2] c.d.job.FileSourceFromInputStreamSource - Could not delete temporary file C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1985
2017-12-19 10:42:49,110 WARN  [pool-2-thread-5] c.d.job.FileSourceFromInputStreamSource - Could not delete temporary file C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1987
2017-12-19 10:42:49,110 INFO  [pool-2-thread-5] c.d.w.e.AsynchronousConversionResponse - Sending exceptional response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@1712035e
com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2017-12-19 10:46:57,277 INFO  [Grizzly-worker(2)] c.d.w.e.AsynchronousConversionResponse - Registered conversion request for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@63f498f
2017-12-19 10:46:57,277 INFO  [pool-2-thread-4] c.d.c.msoffice.MicrosoftWordBridge - Requested conversion from C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1989 (application/vnd.com.documents4j.any-msword) to C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1990 (application/pdf)
2017-12-19 10:47:18,181 WARN  [pool-2-thread-4] c.d.job.FileSourceFromInputStreamSource - Could not delete temporary file C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1989
2017-12-19 10:47:18,181 INFO  [pool-2-thread-4] c.d.w.e.AsynchronousConversionResponse - Sending exceptional response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@63f498f
com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2017-12-19 10:53:08,327 INFO  [Grizzly-worker(1)] c.d.w.e.AsynchronousConversionResponse - Registered conversion request for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@f6750e
2017-12-19 10:53:08,327 INFO  [pool-2-thread-6] c.d.c.msoffice.MicrosoftWordBridge - Requested conversion from C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1991 (application/vnd.com.documents4j.any-msword) to C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1992 (application/pdf)
2017-12-19 10:53:29,138 WARN  [pool-2-thread-6] c.d.job.FileSourceFromInputStreamSource - Could not delete temporary file C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1991
2017-12-19 10:53:29,138 INFO  [pool-2-thread-6] c.d.w.e.AsynchronousConversionResponse - Sending exceptional response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@f6750e
com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]
2017-12-19 10:55:15,547 INFO  [Grizzly-worker(1)] c.d.w.e.AsynchronousConversionResponse - Registered conversion request for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@2cb67099
2017-12-19 10:55:15,547 INFO  [pool-2-thread-7] c.d.c.msoffice.MicrosoftWordBridge - Requested conversion from C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1993 (application/vnd.com.documents4j.any-msword) to C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1994 (application/pdf)
2017-12-19 10:55:36,576 WARN  [pool-2-thread-7] c.d.job.FileSourceFromInputStreamSource - Could not delete temporary file C:\Windows\TEMP\1512472475526-0\9966329a-4eb5-406b-9bc3-3d4f75e952e2\temp1993
2017-12-19 10:55:36,576 INFO  [pool-2-thread-7] c.d.w.e.AsynchronousConversionResponse - Sending exceptional response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@2cb67099
com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78) ~[documents4j-server-standalone-1.0.3-shaded.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_151]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_151]

**Comment by raphw** [comment]
Does the server have permissions to read/write/execute in its target folder?

**Comment by ikeachen01** [comment]
Yes.
After the exception occurs, the conversion will fail (because the office driver bridge is locked).

**Comment by ikeachen01** [comment]
Yes.
After the exception occurs, the conversion will fail (because the office driver bridge is locked).
The client sends the new conversion request to server and will get the error message「can not complete conversion」. The log of server is 「Could not access target file」.

**Comment by ikeachen01** [comment]
Hi raphw.
What is the MS-Office version that you test the documents4j-server-standalone-1.0.3-shaded.jar ?

**Comment by raphw** [comment]
Office 2010.

**Comment by ikeachen01** [comment]
Hi Rafael,
my team has solved this question.

The soluation is to do the 1~4 settings.
1.mkdir C:\Windows\SysWOW64\config\systemprofile\Desktop
2.mkdir C:\Windows\System32\config\systemprofile\Desktop
3.mkdir TEMPDIR=%coverterpath%\temp
4. install the office 2016

Do you have the plan to propose the new documents4j-server-standalone.jar ?
And when?

Thanks a lot.

**Comment by raphw** [comment]
Yes, this has always been necessary and is mentioned in the documentation for when running documents4j as a service: http://documents4j.com/

I did not know about step 3 but I wonder if this is even valid syntax? Of course, a temporary folder must be set on Windows.

**Comment by ikeachen01** [comment]
Even I did 1-3 settings, and the ms office was 2010, and after the exception occured, the new request  failed to convert a doc file to a pdf file.
1.mkdir C:\Windows\SysWOW64\config\systemprofile\Desktop
2.mkdir C:\Windows\System32\config\systemprofile\Desktop
3.mkdir TEMPDIR=%coverterpath%\temp

**Comment by raphw** [comment]
Do you mean this did or did not work?

**Comment by ikeachen01** [comment]
It worked when I installed the office 2016 with the settings 1-3.
It did not work when I installed the office 2010 with the settings 1-3.

**Comment by raphw** [comment]
That is strange, it works without problems in my environment.

**Comment by ikeachen01** [comment]
Sigh.
I think I understand your meaning.
Everything is ok.
That's all.

**Comment by badilaz** [comment]
this happens also on my environment if I start the process automatically as a windows service (on server start up)
while if I start manually the service, it works without problem

**Comment by raphw** [comment]
Did you setup your machine to allow running GUI applications as a service as described in the documentation?
