### ISSUE TITLE
MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor

### ISSUE THREAD

**Issue by Zelthaz** [documents4j/documents4j#55]
Hello

I have this problem.

`class com.documents4j.conversion.msoffice.MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor
	at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:32)
	at com.documents4j.conversion.ExternalConverterDiscovery.makeAll(ExternalConverterDiscovery.java:42)
	at com.documents4j.conversion.ExternalConverterDiscovery.loadConfiguration(ExternalConverterDiscovery.java:85)
	at com.documents4j.conversion.DefaultConversionManager.<init>(DefaultConversionManager.java:22)
	at com.documents4j.job.LocalConverter.makeConversionManager(LocalConverter.java:79)
	at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:51)
	at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:186)
`

Notes:
- MS Office is installed.
- The PDF/XPS add-on is installed in MS Office.

Please. 
How can I solve this error?

**Comment by raphw** [comment]
Is there a cause for the exception down the stack? From this fragment of the error message, it is hard to tell.
