### ISSUE TITLE
com.documents4j.throwables.ConverterAccessException: The converter could not process the request

### ISSUE THREAD

**Issue by parag07sid** [documents4j/documents4j#56]
com.documents4j.throwables.ConverterAccessException: The converter could not process the request
	at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.ws.ConverterNetworkProtocol$Status.resolve(ConverterNetworkProtocol.java:98)
	at com.documents4j.job.WebserviceRequestFutureWrapper.handle(WebserviceRequestFutureWrapper.java:48)
	at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:38)
	at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:13)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by raphw** [comment]
Maybe MS Word has a glitch for some documents, can you reproduce without using documents4j?

**Comment by parag07sid** [comment]
I have 3-4 different docx templates which i am filling with data stored in database and then converting them to pdf using document4j. It works for 1-3 days and then it gives this error. If I restart document4j server it works for next 1-2 days. This error keeps coming with no additional details.
com.documents4j.throwables.ConverterAccessException: The converter could not process the request
at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117)
at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
at com.documents4j.ws.ConverterNetworkProtocol$Status.resolve(ConverterNetworkProtocol.java:98)
at com.documents4j.job.WebserviceRequestFutureWrapper.handle(WebserviceRequestFutureWrapper.java:48)
at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:38)
at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:13)
at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)


   On Tuesday, 28 August, 2018, 3:10:08 AM GMT-4, Rafael Winterhalter <notifications@github.com> wrote:  
 
 
Maybe MS Word has a glitch for some documents, can you reproduce without using documents4j?

**Comment by parag07sid** [comment]
my code is very straight forward:

converter = RemoteConverter.builder().baseFolder(new File("C:\\clinaff mntrtool\\temp")).workerPool(20, 25, 2, TimeUnit.SECONDS).requestTimeout(10, TimeUnit.SECONDS).baseUri("http://localhost:9998").build();

getDocToPDFConverterService().getConverter().convert(new File("c:\\temp\\"+fileName+".docx")).as(DocumentType.MS_WORD)
		.to(new File("c:\\temp\\"+fileName+".pdf")).as(DocumentType.PDF).prioritizeWith(1000).execute();

Does this code needs any correction to fix above error?

**Comment by raphw** [comment]
No, the code is correct. It seems to be a problem at the remote converter, the exception is merely translated from the server to the client.

**Comment by parag07sid** [comment]
okay. So how to fix this?
I am using com.documents4j.job.RemoteConerter from documents4j-client-standalone-1.0.3-shaded.jar

**Comment by raphw** [comment]
Does the server log contain any more hints?

**Comment by parag07sid** [comment]
I have not configured server logs. How to do that?


Sent from Yahoo Mail for iPhone


On Friday, August 31, 2018, 12:53 AM, Rafael Winterhalter <notifications@github.com> wrote:


Does the server log contain any more hints?

**Comment by raphw** [comment]
Run with the -? option to display all commands.

**Comment by raphw** [comment]
Ah, I never tried Java 9, have you checked if that is the problem?

**Comment by raphw** [comment]
For the logging add --level debug

**Comment by parag07sid** [comment]
not able to attach files..here is the stack trace

java.lang.ClassNotFoundException: org.osgi.framework.BundleReference
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
        at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
        at org.glassfish.jersey.internal.util.ReflectionHelper$2.run(ReflectionHelper.java:264) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at org.glassfish.jersey.internal.util.ReflectionHelper$2.run(ReflectionHelper.java:249) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at java.base/java.security.AccessController.doPrivileged(Native Method) [na:na]
        at org.glassfish.jersey.internal.util.ReflectionHelper.<clinit>(ReflectionHelper.java:1412) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at org.glassfish.jersey.server.ResourceConfig$State.<init>(ResourceConfig.java:111) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at org.glassfish.jersey.server.ResourceConfig.<init>(ResourceConfig.java:351) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at org.glassfish.jersey.server.ResourceConfig$WrappingResourceConfig.<init>(ResourceConfig.java:1016) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at org.glassfish.jersey.server.ResourceConfig.forApplication(ResourceConfig.java:314) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at com.documents4j.builder.ConverterServerBuilder.build(ConverterServerBuilder.java:201) [documents4j-server-standalone-1.0.3-shaded.jar:na]
        at com.documents4j.standalone.StandaloneServer.main(StandaloneServer.java:51) [documents4j-server-standalone-1.0.3-shaded.jar:na]
2018-09-20 10:20:48,389 INFO  [main] o.glassfish.jersey.internal.ServiceFinder - Running in a non-OSGi environment
2018-09-20 10:20:48,464 INFO  [main] o.g.jersey.server.ApplicationHandler - Initiating Jersey application, version Jersey: 2.6 2014-02-18 21:52:53...
2018-09-20 10:20:48,580 DEBUG [main] o.g.j.i.util.collection.DataStructures - USING LTQ class:class java.util.concurrent.LinkedTransferQueue
2018-09-20 10:20:48,698 INFO  [main] o.g.j.p.internal.RequestExecutorFactory - "No custom request executor provider registrations found - using default: [org.glassfish.jersey.server.ServerManagedAsyncExec
2018-09-20 10:20:48,704 INFO  [main] o.g.jersey.server.ApplicationHandler - Jersey application initialized.
Root Resource Classes:
  com.documents4j.ws.endpoint.ConverterResource
Global Response Filters:
   org.glassfish.jersey.server.filter.EncodingFilter
Global Reader Interceptors:
   org.glassfish.jersey.message.GZipEncoder
   org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor
Global Writer Interceptors:
   org.glassfish.jersey.message.GZipEncoder
   org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor
   org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor
Message Body Readers:
   org.glassfish.jersey.message.internal.XmlJaxbElementProvider$App
   org.glassfish.jersey.message.internal.FormMultivaluedMapProvider
   org.glassfish.jersey.message.internal.DocumentProvider
   org.glassfish.jersey.message.internal.ReaderProvider
   org.glassfish.jersey.message.internal.BasicTypesMessageProvider
   org.glassfish.jersey.message.internal.XmlRootObjectJaxbProvider$General
   org.glassfish.jersey.message.internal.StringMessageProvider
   org.glassfish.jersey.message.internal.XmlCollectionJaxbProvider$App
   org.glassfish.jersey.message.internal.XmlRootElementJaxbProvider$App
   org.glassfish.jersey.message.internal.XmlJaxbElementProvider$General
   org.glassfish.jersey.message.internal.XmlCollectionJaxbProvider$Text
   org.glassfish.jersey.message.internal.XmlCollectionJaxbProvider$General
   org.glassfish.jersey.message.internal.SourceProvider$DomSourceReader
   org.glassfish.jersey.message.internal.XmlJaxbElementProvider$Text
   org.glassfish.jersey.message.internal.SourceProvider$SaxSourceReader
   org.glassfish.jersey.message.internal.XmlRootObjectJaxbProvider$Text
   org.glassfish.jersey.message.internal.RenderedImageProvider
   org.glassfish.jersey.message.internal.XmlRootElementJaxbProvider$General
   org.glassfish.jersey.message.internal.XmlRootElementJaxbProvider$Text
   org.glassfish.jersey.message.internal.XmlRootObjectJaxbProvider$App
   org.glassfish.jersey.message.internal.DataSourceProvider
   org.glassfish.jersey.message.internal.ByteArrayProvider
   org.glassfish.jersey.message.internal.FormProvider
   org.glassfish.jersey.message.internal.InputStreamProvider
   org.glassfish.jersey.message.internal.FileProvider
   org.glassfish.jersey.message.internal.SourceProvider$StreamSourceReader
Message Body Writers:
   org.glassfish.jersey.message.internal.XmlJaxbElementProvider$App
   org.glassfish.jersey.message.internal.FormMultivaluedMapProvider
   org.glassfish.jersey.message.internal.XmlJaxbElementProvider$Text
   org.glassfish.jersey.message.internal.StreamingOutputProvider
   org.glassfish.jersey.message.internal.DocumentProvider
   org.glassfish.jersey.message.internal.ReaderProvider
   org.glassfish.jersey.message.internal.BasicTypesMessageProvider
   org.glassfish.jersey.message.internal.RenderedImageProvider
   org.glassfish.jersey.message.internal.XmlRootElementJaxbProvider$General
   org.glassfish.jersey.server.ChunkedResponseWriter
   org.glassfish.jersey.message.internal.StringMessageProvider
   org.glassfish.jersey.message.internal.XmlCollectionJaxbProvider$App
   org.glassfish.jersey.message.internal.XmlRootElementJaxbProvider$App
   org.glassfish.jersey.message.internal.XmlRootElementJaxbProvider$Text
   org.glassfish.jersey.message.internal.XmlJaxbElementProvider$General
   org.glassfish.jersey.message.internal.XmlCollectionJaxbProvider$Text
   org.glassfish.jersey.message.internal.DataSourceProvider
   org.glassfish.jersey.message.internal.XmlCollectionJaxbProvider$General
   org.glassfish.jersey.message.internal.SourceProvider$SourceWriter
   org.glassfish.jersey.message.internal.ByteArrayProvider
   org.glassfish.jersey.message.internal.FormProvider
   org.glassfish.jersey.message.internal.InputStreamProvider
   org.glassfish.jersey.message.internal.FileProvider

2018-09-20 10:20:48,761 DEBUG [main] org.glassfish.grizzly.utils.DataStructures - USING LTQ class:class java.util.concurrent.LinkedTransferQueue
2018-09-20 10:20:48,916 DEBUG [Grizzly(1) SelectorRunner] o.g.grizzly.nio.DefaultSelectionKeyHandler - KEY IS REGISTERED: sun.nio.ch.SelectionKeyImpl@8d0f43b
2018-09-20 10:20:48,917 INFO  [main] o.g.grizzly.http.server.NetworkListener - Started listener bound to [localhost:9998]
2018-09-20 10:20:48,920 INFO  [main] c.d.w.a.StandaloneWebConverterConfiguration - Standalone conversion server is starting: starting up local converter
2018-09-20 10:20:48,944 DEBUG [main] org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\AppData\Local\Temp\3\1537453248924-0\word_start175243357.vbs""] in C:\Users\
2018-09-20 10:20:48,952 DEBUG [main] org.zeroturnaround.exec.ProcessExecutor - Started Process[pid=14992, exitValue="not exited"]
2018-09-20 10:20:49,187 DEBUG [WaitForProcess-Process[pid=14992, exitValue="not exited"]] org.zeroturnaround.exec.WaitForProcess - Process[pid=14992, exitValue=3] stopped with exit code 3
2018-09-20 10:20:49,190 INFO  [main] c.d.c.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
2018-09-20 10:20:49,195 DEBUG [main] org.zeroturnaround.exec.ProcessExecutor - Executing [cmd, /S, /C, ""C:\Users\AppData\Local\Temp\3\1537453248924-0\excel_start1772565269.vbs""] in C:\Users\
2018-09-20 10:20:49,197 DEBUG [main] org.zeroturnaround.exec.ProcessExecutor - Started Process[pid=17312, exitValue="not exited"]
2018-09-20 10:20:49,544 DEBUG [WaitForProcess-Process[pid=17312, exitValue="not exited"]] org.zeroturnaround.exec.WaitForProcess - Process[pid=17312, exitValue=3] stopped with exit code 3
2018-09-20 10:20:49,546 INFO  [main] c.d.c.msoffice.MicrosoftExcelBridge - From-Microsoft-Excel-Converter was started successfully
2018-09-20 10:20:49,550 INFO  [main] com.documents4j.job.LocalConverter - The documents4j local converter has started successfully
2018-09-20 10:20:49,552 INFO  [main] c.d.w.a.StandaloneWebConverterConfiguration - Standalone conversion server is starting: local converter is started
2018-09-20 10:20:49,553 INFO  [main] o.glassfish.grizzly.http.server.HttpServer - [HttpServer] Started.
Welcome to the documents4j server!
2018-09-20 10:20:49,571 INFO  [main] c.documents4j.standalone.StandaloneServer - Thu Sep 20 10:20:49 EDT 2018: Started server on 'http://localhost:9998'
2018-09-20 10:20:49,573 INFO  [main] c.documents4j.standalone.StandaloneServer - documents4j server is listening at http://localhost:9998
2018-09-20 10:20:49,573 INFO  [main] c.documents4j.standalone.StandaloneServer - documents4j server is writing temporary files to: <temporary folder>
2018-09-20 10:20:49,574 INFO  [main] c.documents4j.standalone.StandaloneServer - documents4j server worker threads: 15 (+30) - timeout: 600000 ms
2018-09-20 10:20:49,574 INFO  [main] c.documents4j.standalone.StandaloneServer - documents4j server process timeout: 300000
2018-09-20 10:20:49,575 INFO  [main] c.documents4j.standalone.StandaloneServer - documents4j server request timeout: 120000
Thu Sep 20 10:20:49 EDT 2018: Started server on 'http://localhost:9998'
The documents4j server is up and running. Hit the enter key to shut it down...

**Comment by raphw** [comment]
It seems like the Jersey container used by documents4j is not supported by Java 9. I am sure it will work if a Java 8 VM was used. You can also try to update the Jersey dependency.

**Comment by yesmanimaran** [comment]
I am also facing the same issue, Getting the following exception
com.documents4j.throwables.ConverterAccessException: The converter could not process the request
	at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.ws.ConverterNetworkProtocol$Status.resolve(ConverterNetworkProtocol.java:98)
	at com.documents4j.job.WebserviceRequestFutureWrapper.handle(WebserviceRequestFutureWrapper.java:48)
	at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:38)
	at com.documents4j.job.WebserviceRequestFutureWrapper.get(WebserviceRequestFutureWrapper.java:13)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

The service goes down 2 days after restarting.   I have also tried hitting the remote conversion server every 5 minutes though  a cron job but that did not help. @raphw @parag07sid

**Comment by raphw** [comment]
I answered your email: This is a Word issue, you might need to add a load balancer and restart a server on failure. Also, try chaning your Word version.

**Comment by yesmanimaran** [comment]
Thanks @raphw . Can you please tell me which version of Word you recommend.  I use Office 365 Home edition. Also i am currently running this on Windows server 2022. do you think this matters also?  should i use windows  10 instead
