### ISSUE TITLE
com.documents4j.conversion.msoffice.MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor

### ISSUE THREAD

**Issue by hellosoboroo** [documents4j/documents4j#57]
Hello

I have this problem.

this is my code 
===========================================
public static void main(String args[]){
	String sourcsFile = "C:/abc.xls";
	String targetFile = "C:/FirmOrderLetter_MYR.pdf";
	

	File execelFile = new File(sourcsFile), target = new File(targetFile);
	
	

	
	IConverter converter = LocalConverter.builder()
                .baseFolder(new File("C:/Users/documents4j/temp"))
                .workerPool(20, 25, 2, TimeUnit.SECONDS)
                .processTimeout(5, TimeUnit.SECONDS)
                .build();

	
	Future<Boolean> conversion = converter
		.convert(execelFile).as(DocumentType.MS_EXCEL)
		.to(target).as(DocumentType.PDF)
		.prioritizeWith(1000)
		.schedule();
    }

==============================================================

this is error log 

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/ket/workspace/ketplm/codebase/WEB-INF/lib/activemq-all-5.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/ket/workspace/ketplm/codebase/WEB-INF/lib/documents4j-server-standalone-1.0.3-shaded.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/ket/workspace/ketplm/codebase/WEB-INF/lib/ie3rdpartylibs.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/ptc/Windchill_10.2/Windchill/srclib/slf4j-log4j12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.lang.IllegalStateException: class com.documents4j.conversion.msoffice.MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor
	at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:32)
	at com.documents4j.conversion.ExternalConverterDiscovery.makeAll(ExternalConverterDiscovery.java:42)
	at com.documents4j.conversion.ExternalConverterDiscovery.loadConfiguration(ExternalConverterDiscovery.java:85)
	at com.documents4j.conversion.DefaultConversionManager.<init>(DefaultConversionManager.java:22)
	at com.documents4j.job.LocalConverter.makeConversionManager(LocalConverter.java:79)
	at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:51)
	at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:186)
	at ext.ket.shared.util.msConverterUtil.main(msConverterUtil.java:33)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:30)
	... 7 more
Caused by: java.lang.NoSuchFieldError: NULL_OUTPUT_STREAM
	at org.zeroturnaround.exec.ProcessExecutor.redirectOutput(ProcessExecutor.java:449)
	at org.zeroturnaround.exec.ProcessExecutor.<init>(ProcessExecutor.java:159)
	at com.documents4j.conversion.AbstractExternalConverter.makePresetProcessExecutor(AbstractExternalConverter.java:54)
	at com.documents4j.conversion.AbstractExternalConverter.runNoArgumentScript(AbstractExternalConverter.java:70)
	at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.runNoArgumentScript(AbstractMicrosoftOfficeBridge.java:51)
	at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.tryStart(AbstractMicrosoftOfficeBridge.java:34)
	at com.documents4j.conversion.msoffice.MicrosoftWordBridge.startUp(MicrosoftWordBridge.java:44)
	at com.documents4j.conversion.msoffice.MicrosoftWordBridge.<init>(MicrosoftWordBridge.java:39)
	... 12 more
Exception in thread "Shutdown hook: com.documents4j.job.LocalConverter" java.lang.NullPointerException
	at com.documents4j.job.LocalConverter.shutDown(LocalConverter.java:100)
	at com.documents4j.job.ConverterAdapter$ConverterShutdownHook.run(ConverterAdapter.java:134)

Notes:
•MS Office is installed. (ver 2010)

[
![jar](https://user-images.githubusercontent.com/42995182/45079109-2d5d0080-b0e1-11e8-830b-613b17b9897b.jpg)
](url)

Please.
 How can I solve this error?

**Comment by raphw** [comment]
Looks like a class path issue: https://github.com/zeroturnaround/zt-exec/issues/49

**Comment by hellosoboroo** [comment]
Thank you very much
This issue has been resolved.
However, the result is another problem
Picture or image can not be expressed

Please.
How can I solve this error?

**Comment by raphw** [comment]
Have you tried to convert the document in Word without documents4j? It might be a word issue.
