### ISSUE TITLE
WindowsXP+Office2007+Java8u55_x86 Excel exception but Word OK

### ISSUE THREAD

**Issue by paladinzh** [documents4j/documents4j#58]
Two question:
1. WindowsXP+Office2007+Java8u55_x86 Excel exception but Word OK, How to fix?
2. How to covert ppt\pptx by documents4j?

10-12 11:21:55.578 I/2924.1,main ExcelConverter.convertToPdf.26: convertToPdf C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls -> C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls.pdf
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
10-12 11:21:55.703 T/2924.1,main AbstractExternalConverter.runNoArgumentScript.53: Execute no-argument script C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\excel_start640924444.vbs
10-12 11:21:55.734 D/2924.1,main MessageLoggers$3.message.42: Executing [cmd, /C, "C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\excel_start640924444.vbs"] in C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office.
10-12 11:21:55.765 D/2924.1,main MessageLoggers$3.message.42: Started java.lang.ProcessImpl@16d4b5c
10-12 11:21:55.781 T/2924.10,Thread-0 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@19a88ad started.
10-12 11:21:55.781 T/2924.11,Thread-1 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@1d94a08 started.
10-12 11:21:58.406 T/2924.10,Thread-0 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@19a88ad finished.
10-12 11:21:58.406 T/2924.11,Thread-1 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@1d94a08 finished.
10-12 11:21:58.406 D/2924.12,WaitForProcess-java.lang.ProcessImpl@16d4b5c MessageLoggers$3.message.42: java.lang.ProcessImpl@16d4b5c stopped with exit code 3
10-12 11:21:58.421 T/2924.12,WaitForProcess-java.lang.ProcessImpl@16d4b5c PumpStreamHandler.stop.201: Joining output thread Thread[Thread-0,5,]...
10-12 11:21:58.421 T/2924.12,WaitForProcess-java.lang.ProcessImpl@16d4b5c PumpStreamHandler.stop.211: Joining error thread Thread[Thread-1,5,]...
10-12 11:21:58.421 T/2924.12,WaitForProcess-java.lang.ProcessImpl@16d4b5c PumpStreamHandler.flush.225: Flushing output stream org.apache.commons.io.output.TeeOutputStream@1824a5...
10-12 11:21:58.421 T/2924.12,WaitForProcess-java.lang.ProcessImpl@16d4b5c PumpStreamHandler.flush.234: Flushing error stream org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@718e07...
10-12 11:21:58.421 I/2924.1,main MicrosoftExcelBridge.startUp.49: From-Microsoft-Excel-Converter was started successfully
10-12 11:21:58.437 T/2924.1,main AbstractExternalConverter.runNoArgumentScript.53: Execute no-argument script C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\word_start127664382.vbs
10-12 11:21:58.437 D/2924.1,main MessageLoggers$3.message.42: Executing [cmd, /C, "C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\word_start127664382.vbs"] in C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office.
10-12 11:21:58.453 D/2924.1,main MessageLoggers$3.message.42: Started java.lang.ProcessImpl@be92ad
10-12 11:21:58.453 T/2924.13,Thread-2 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@1d00ba2 started.
10-12 11:21:58.453 T/2924.14,Thread-3 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@620897 started.
10-12 11:21:59.750 T/2924.13,Thread-2 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@1d00ba2 finished.
10-12 11:21:59.750 T/2924.14,Thread-3 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@620897 finished.
10-12 11:21:59.750 D/2924.15,WaitForProcess-java.lang.ProcessImpl@be92ad MessageLoggers$3.message.42: java.lang.ProcessImpl@be92ad stopped with exit code 3
10-12 11:21:59.750 T/2924.15,WaitForProcess-java.lang.ProcessImpl@be92ad PumpStreamHandler.stop.201: Joining output thread Thread[Thread-2,5,]...
10-12 11:21:59.750 T/2924.15,WaitForProcess-java.lang.ProcessImpl@be92ad PumpStreamHandler.stop.211: Joining error thread Thread[Thread-3,5,]...
10-12 11:21:59.750 T/2924.15,WaitForProcess-java.lang.ProcessImpl@be92ad PumpStreamHandler.flush.225: Flushing output stream org.apache.commons.io.output.TeeOutputStream@6d460a...
10-12 11:21:59.750 T/2924.15,WaitForProcess-java.lang.ProcessImpl@be92ad PumpStreamHandler.flush.234: Flushing error stream org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@aabfb7...
10-12 11:21:59.750 I/2924.1,main MicrosoftWordBridge.startUp.43: From-Microsoft-Word-Converter was started successfully
10-12 11:21:59.765 I/2924.1,main LocalConverter.<init>.49: The documents4j local converter has started successfully
10-12 11:21:59.781 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.53: Attempt to execute conversion
10-12 11:21:59.781 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.60: Source fetched: C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls
10-12 11:21:59.781 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.66: Run method locked wrapped future for source C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls
10-12 11:21:59.781 I/2924.16,pool-1-thread-1 AbstractMicrosoftOfficeBridge.doStartConversion.63: Requested conversion from C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls (application/vnd.com.documents4j.any-msexcel) to C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls.pdf (application/pdf)
10-12 11:21:59.781 T/2924.16,pool-1-thread-1 MicrosoftExcelTargetNameCorrectorAndLockManager.beforeStart.29: Attempting to acquire MS Excel conversion lock
10-12 11:21:59.781 T/2924.16,pool-1-thread-1 MicrosoftExcelTargetNameCorrectorAndLockManager.beforeStart.31: Acquired MS Excel conversion lock
10-12 11:21:59.781 D/2924.16,pool-1-thread-1 MessageLoggers$3.message.42: Executing [cmd, /C, "C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\excel_convert1441713302.vbs C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls.pdf 999"] in C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office.
10-12 11:21:59.796 D/2924.16,pool-1-thread-1 MessageLoggers$3.message.42: Started java.lang.ProcessImpl@1d18a36
10-12 11:21:59.796 T/2924.17,Thread-4 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@107f58b started.
10-12 11:21:59.796 T/2924.18,Thread-5 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@1d746e2 started.
10-12 11:21:59.796 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.71: Context fetched for source C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls: com.documents4j.job.LocalConversionContext@e976ae
10-12 11:21:59.812 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.73: Underlying future created for source C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls: com.documents4j.conversion.ProcessFutureWrapper@108b652
10-12 11:21:59.812 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.77: Blocking during external conversion for source C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\test_tmp.xls: com.documents4j.conversion.ProcessFutureWrapper@108b652
10-12 11:22:01.171 T/2924.18,Thread-5 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@1d746e2 finished.
10-12 11:22:01.171 D/2924.20,WaitForProcess-java.lang.ProcessImpl@1d18a36 MessageLoggers$3.message.42: java.lang.ProcessImpl@1d18a36 stopped with exit code -3
10-12 11:22:01.171 T/2924.17,Thread-4 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@107f58b finished.
10-12 11:22:01.171 T/2924.20,WaitForProcess-java.lang.ProcessImpl@1d18a36 PumpStreamHandler.stop.201: Joining output thread Thread[Thread-4,5,main]...
10-12 11:22:01.171 T/2924.20,WaitForProcess-java.lang.ProcessImpl@1d18a36 PumpStreamHandler.stop.211: Joining error thread Thread[Thread-5,5,]...
10-12 11:22:01.171 T/2924.20,WaitForProcess-java.lang.ProcessImpl@1d18a36 PumpStreamHandler.flush.225: Flushing output stream org.apache.commons.io.output.TeeOutputStream@1ae8c36...
10-12 11:22:01.171 T/2924.20,WaitForProcess-java.lang.ProcessImpl@1d18a36 PumpStreamHandler.flush.234: Flushing error stream org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@16969f3...
10-12 11:22:01.171 T/2924.20,WaitForProcess-java.lang.ProcessImpl@1d18a36 MicrosoftExcelTargetNameCorrectorAndLockManager.afterStop.38: Released MS Excel conversion lock
10-12 11:22:01.171 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.108: Conversion caused an error
java.util.concurrent.ExecutionException: The conversion finished unsuccessful
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:50)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	... 6 more
10-12 11:22:01.187 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.128: Release locks for FailedConversionFuture{exception=com.documents4j.throwables.FileSystemInteractionException, message=Could not access target file}
10-12 11:22:01.187 E/2924.1,main PrinterController.prepare.113: converter com.anylian.eprinting.printersdk.converter.office.ExcelConverter@4aed64 convertToPdf Exception:
java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:212)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
	at com.anylian.eprinting.printersdk.converter.office.ExcelConverter.convertToPdf(ExcelConverter.java:41)
	at com.anylian.eprinting.printersdk.PrinterController.prepare(PrinterController.java:108)
	at com.anylian.eprinting.printersdk.PrinterControllerTest.testPrepare_fail(PrinterControllerTest.java:456)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
10-12 11:22:01.187 W/2924.1,main PrinterControllerTest.testPrepare_fail.457: prepare End false

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:201)
	at com.anylian.eprinting.printersdk.PrinterControllerTest.testPrepare_fail(PrinterControllerTest.java:458)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

10-12 11:22:01.187 T/2924.16,pool-1-thread-1 AbstractFutureWrappingPriorityFuture.run.130: Locks for FailedConversionFuture{exception=com.documents4j.throwables.FileSystemInteractionException, message=Could not access target file} are released
10-12 11:22:01.203 T/2924.9,Shutdown hook: com.documents4j.job.LocalConverter AbstractExternalConverter.runNoArgumentScript.53: Execute no-argument script C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\excel_shutdown621935925.vbs
10-12 11:22:01.203 D/2924.9,Shutdown hook: com.documents4j.job.LocalConverter MessageLoggers$3.message.42: Executing [cmd, /C, "C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\excel_shutdown621935925.vbs"] in C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office.
10-12 11:22:01.218 D/2924.9,Shutdown hook: com.documents4j.job.LocalConverter MessageLoggers$3.message.42: Started java.lang.ProcessImpl@1530c8d
10-12 11:22:01.218 T/2924.21,Thread-6 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@1838c55 started.
10-12 11:22:01.218 T/2924.22,Thread-7 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@182b784 started.
10-12 11:22:01.484 T/2924.21,Thread-6 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@1838c55 finished.
10-12 11:22:01.484 T/2924.22,Thread-7 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@182b784 finished.
10-12 11:22:01.484 D/2924.23,WaitForProcess-java.lang.ProcessImpl@1530c8d MessageLoggers$3.message.42: java.lang.ProcessImpl@1530c8d stopped with exit code 3
10-12 11:22:01.484 T/2924.23,WaitForProcess-java.lang.ProcessImpl@1530c8d PumpStreamHandler.stop.201: Joining output thread Thread[Thread-6,5,]...
10-12 11:22:01.484 T/2924.23,WaitForProcess-java.lang.ProcessImpl@1530c8d PumpStreamHandler.stop.211: Joining error thread Thread[Thread-7,5,]...
10-12 11:22:01.484 T/2924.23,WaitForProcess-java.lang.ProcessImpl@1530c8d PumpStreamHandler.flush.225: Flushing output stream org.apache.commons.io.output.TeeOutputStream@1ea4d2e...
10-12 11:22:01.484 T/2924.23,WaitForProcess-java.lang.ProcessImpl@1530c8d PumpStreamHandler.flush.234: Flushing error stream org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@12db923...
10-12 11:22:01.500 I/2924.9,Shutdown hook: com.documents4j.job.LocalConverter MicrosoftExcelBridge.shutDown.57: From-Microsoft-Excel-Converter was shut down successfully
10-12 11:22:01.500 T/2924.9,Shutdown hook: com.documents4j.job.LocalConverter AbstractExternalConverter.runNoArgumentScript.53: Execute no-argument script C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\word_shutdown703420545.vbs
10-12 11:22:01.500 D/2924.9,Shutdown hook: com.documents4j.job.LocalConverter MessageLoggers$3.message.42: Executing [cmd, /C, "C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office\word_shutdown703420545.vbs"] in C:\_Space\iCode\Git_Anylian\testRes\test_tmp\Office.
10-12 11:22:01.515 D/2924.9,Shutdown hook: com.documents4j.job.LocalConverter MessageLoggers$3.message.42: Started java.lang.ProcessImpl@f1d144
10-12 11:22:01.515 T/2924.24,Thread-8 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@15f3281 started.
10-12 11:22:01.515 T/2924.25,Thread-9 StreamPumper.run.118: org.zeroturnaround.exec.stream.StreamPumper@3ce6c4 started.
10-12 11:22:01.828 T/2924.25,Thread-9 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@3ce6c4 finished.
10-12 11:22:01.828 D/2924.26,WaitForProcess-java.lang.ProcessImpl@f1d144 MessageLoggers$3.message.42: java.lang.ProcessImpl@f1d144 stopped with exit code 3
10-12 11:22:01.828 T/2924.24,Thread-8 StreamPumper.run.134: org.zeroturnaround.exec.stream.StreamPumper@15f3281 finished.
10-12 11:22:01.828 T/2924.26,WaitForProcess-java.lang.ProcessImpl@f1d144 PumpStreamHandler.stop.201: Joining output thread Thread[Thread-8,5,main]...
10-12 11:22:01.828 T/2924.26,WaitForProcess-java.lang.ProcessImpl@f1d144 PumpStreamHandler.stop.211: Joining error thread Thread[Thread-9,5,]...
10-12 11:22:01.843 T/2924.26,WaitForProcess-java.lang.ProcessImpl@f1d144 PumpStreamHandler.flush.225: Flushing output stream org.apache.commons.io.output.TeeOutputStream@4d986d...
10-12 11:22:01.843 T/2924.26,WaitForProcess-java.lang.ProcessImpl@f1d144 PumpStreamHandler.flush.234: Flushing error stream org.zeroturnaround.exec.stream.slf4j.Slf4jInfoOutputStream@8a6094...
10-12 11:22:01.843 I/2924.9,Shutdown hook: com.documents4j.job.LocalConverter MicrosoftWordBridge.shutDown.51: From-Microsoft-Word-Converter was shut down successfully
10-12 11:22:01.843 I/2924.9,Shutdown hook: com.documents4j.job.LocalConverter ConverterAdapter.deregisterShutdownHook.114: Tried to deregister shut down hook in shut down period
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at com.documents4j.job.ConverterAdapter.deregisterShutdownHook(ConverterAdapter.java:112)
	at com.documents4j.job.ConverterAdapter.shutDown(ConverterAdapter.java:98)
	at com.documents4j.job.LocalConverter.shutDown(LocalConverter.java:98)
	at com.documents4j.job.ConverterAdapter$ConverterShutdownHook.run(ConverterAdapter.java:125)
10-12 11:22:01.859 I/2924.9,Shutdown hook: com.documents4j.job.LocalConverter LocalConverter.shutDown.100: The documents4j local converter has shut down successfully

Process finished with exit code -1

**Comment by raphw** [comment]
Did you try to generate a PDF in Excel manually? It might be a problem with the origin document.

**Comment by paladinzh** [comment]
WindowsXP+Office2007+Java8u55_x86 Excel exception but Word OK, How to fix?
--After install virtual printer exe，it works. why?

How to covert ppt\pptx by documents4j?
-- any solution?
