### ISSUE TITLE
The input file seems to be corrupt

### ISSUE THREAD

**Issue by 993198101** [documents4j/documents4j#61]
`com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

This situation occurs when convert to pdf quickly, not always.  I have created a folder C:\Windows\SysWOW64\config\systemprofile\Desktop ，but not work.

this is my code  
`    private volatile IConverter iConverter;

    @PostConstruct
    void init() {
        iConverter = LocalConverter.builder()
                .baseFolder(new File(doc4jtemp))
                .processTimeout(5L, TimeUnit.MINUTES)
                .workerPool(15,30,10,TimeUnit.MINUTES)
                .build();
    }
    public void doc2pdf(String docPath, String pdfPath) {
        File source = new File(docPath);
        File target = new File(pdfPath);
        iConverter.convert(source).as(DocumentType.MS_WORD)
                .to(target).as(DocumentType.PDF)
                .execute();
    }
`

**Comment by raphw** [comment]
Seems to me like you are not closing a stream to the file that writes the input or maybe you are holding a lock on the output. Might that be the case?

**Comment by 993198101** [comment]
see
