### ISSUE TITLE
The converter seems to be shut down

### ISSUE THREAD

**Issue by jcromerogar** [documents4j/documents4j#62]
I using IConverter successfully in a local environmet but when I do a development in a server-test environment, I am getting this exception "The converter seems to be shut down" when convert a document to PDF. The PDF-file is created in the destination folder but it is empty.

The tracelog which Tomcat shown is:

may 28, 2019 5:10:08 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [es.dxd.aldeasa.PortalWeb.util.DocViewer] in context with path [/PortalWeb] threw exception
com.documents4j.throwables.ConverterAccessException: The converter seems to be shut down
	at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Could you help me, please??

Thanks a lot in advance.

JC

**Comment by raphw** [comment]
Hi, that means that the MS Word process seems to be shut down. Maybe it failed to start up. Are you running the server as a service or directly as a user?

**Comment by jcromerogar** [comment]
just one question, is it necessary that the MS Word is installed in the machine where is being executing the IConverter ?

thanks in advance.

**Comment by raphw** [comment]
If you are running a conversion server or the lical converter, yes, this is necessary.

**Comment by yasl88** [comment]
> Hi, that means that the MS Word process seems to be shut down. Maybe it failed to start up. Are you running the server as a service or directly as a user?

Hi, I have the same error. The MS word is installed in my windows server 2016 ( 64 bit), while it says the converter failed to start. I am using localConverter.
Thanks

**Comment by raphw** [comment]
Is there an error message? Did you try to run the `converter_start.vbs` script manually to see if there is an error message popping up?

**Comment by yasl88** [comment]
I have this exception threw while I am trying to convert a word file to pdf.
com.documents4j.throwables.ConverterAccessException: The converter seems to be shut down
	at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117) ~[documents4j-util-all-1.1.1.jar:?]
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75) ~[documents4j-util-all-1.1.1.jar:?]
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70) ~[documents4j-transformer-api-1.1.1.jar:?]
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48) ~[documents4j-util-transformer-process-1.1.1.jar:?]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36) ~[documents4j-util-transformer-process-1.1.1.jar:?]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11) ~[documents4j-util-transformer-process-1.1.1.jar:?]
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78) ~[documents4j-util-conversion-1.1.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_211]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]


I also ran word_convert.vbs through command line and saw the below error.
**word_convert.vbs(83, 1) Microsoft VBScript runtime error: Subscript out of range** 

Thanks a lot for your help.

**Comment by raphw** [comment]
You need to run `converter_start.vbs` first. The conversion script takes the input file, the output file and a number (999 for pdf) as arguments.

**Comment by yasl88** [comment]
Can you please give me the link for converter_start.vbs? Is it in the document4j library. I cloud not find it.

**Comment by raphw** [comment]
The scripts are all in here: https://github.com/documents4j/documents4j/tree/master/documents4j-transformer-msoffice/documents4j-transformer-msoffice-word/src/main/resources

**Comment by yasl88** [comment]
Thanks! 
I can see word process is created after I run word_start.vbs. A pdf file can also be generated after I run word_convert.vbs.

**Comment by raphw** [comment]
The converter only runs these scripts. If it does not work using it, there must be something wrong with another file.

**Comment by yasl88** [comment]
Do you see any reason why I still get the " The converter seems to be shut down" error even when I can successfully run word_start.vbs and word_convert.vbs successfully?

**Comment by raphw** [comment]
Did you try running the assertion script to see if it is actually responsive?

**Comment by nycolasoliveira** [comment]
Hi, i have the same error too. By suggestions i ran the `word_convert.vbs ` and `word_start`, and the pdf is generate correctly. My application (java) was working fine, but now the process appear this error. 

ps: the `word_start.vbs` need parameter for run?

**Comment by yasl88** [comment]
> Did you try running the assertion script to see if it is actually responsive?

Hi Raphw, eventually I found it is the permission issue that tomcat can not bring up the MS office instance. Granting Tomcat admin permission can resolve it. Thanks for your assistance.

**Comment by nycolasoliveira** [comment]
Do you can describe this solution? Pearhaps this its my problem too.

**Comment by raphw** [comment]
If you are running the converter with a different user (e.g. the service user), it must be allowed to start Word.

**Comment by nycolasoliveira** [comment]
My application its running with tomcat as service of windows. Changed my app for running into tomcat and it's working fine.

**Comment by raphw** [comment]
For running as a service, the webpage describes a few extra steps that are necessary.

**Comment by stracymines** [comment]
I know this is a relatively old thread, so please redirect me to the right location if this is the incorrect location to continue this conversation.

@yasl88 could you clarify what exactly you mean by "Granting Tomcat admin permission can resolve it" ? 

I am also trying to use documents4j inside of an application that is run using Tomcat. I see on the website that there are instructions for running documents4j as a service which I have followed. These work great if Tomcat is run as the "Local System" user but for security reasons I want to run Tomcat as a different user that has permissions locked down a bit more. When I use this other user, I am unable to convert documents. I have tried to grant appropriate permissions but seem to be stuck, as I see these logs:

[https-openssl-apr-8447-exec-2] INFO com.documents4j.conversion.msoffice.MicrosoftExcelBridge - From-Microsoft-Excel-Converter was started successfully
[https-openssl-apr-8447-exec-2] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
[https-openssl-apr-8447-exec-2] INFO com.documents4j.job.LocalConverter - The documents4j local converter has started successfully

Which would indicate to me that WINWORD.exe would have been started, but it does not show up in the task manager (it does as when running as Local System). Then, on actual conversion attempt I see these exceptions:

java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
...
Caused by: com.documents4j.throwables.ConverterAccessException: The converter seems to be shut down
	at com.documents4j.util.Reaction$ConverterAccessExceptionBuilder.make(Reaction.java:117)

Is what I am trying to do with converting a word doc to pdf through documents4j being hosted in a Tomcat that is run by a user other than Local System even possible? I am a bit lost on what files/folders I would need to grant the user permission to.

**Comment by raphw** [comment]
Have you checked documents4j.com section about running the server as a service? Additionally, Tomcat needs to be able to write to the file system by the user it is running under.

**Comment by stracymines** [comment]
Hi there @raphw, yes I have followed that section. Following that section makes it work when tomcat is running as "Local System" but it does not work when running as a different user. I would assume that if the user tomcat is running as has a desktop with those same folders it should work?

**Comment by raphw** [comment]
I assume but never tried it. If you are running a user headless, Word is not working as expected without these folders existing.

**Comment by DevasishBanerjee** [comment]
I am continuously getting this error when I am deploying my application in a Windows server with Tomcat 9 as a service:-

com.documents4j.throwables.ConverterAccessException: The converter seems to be shut down

It is working fine in my Eclipse IDE. Kindly let me know what is the issue. Also, I have tried "For running as a service, the webpage describes a few extra steps that are necessary." But still it does not work.

**Comment by raphw** [comment]
There is a section on running this as a service on the webpage. Did you attempt to set everything up that way?

**Comment by DevasishBanerjee** [comment]
Do you mean the site documents4j.com? Where exactly is that?

**Comment by DevasishBanerjee** [comment]
I was trying to deploy with the command java -jar documents4j-server-standalone-shaded.jar http://localhost:9998. I was using the version 1.0.3. A huge amout of errors occured. What is the way forward?

**Comment by DevasishBanerjee** [comment]
Well now I installed documents4j-server-standalone-shaded.jar and its showing me that the service is up and running. However I am still getting the same error. Kindly help me.
