### ISSUE TITLE
ConversionInputException: The input file seems to be corrupt

### ISSUE THREAD

**Issue by Subash2891** [documents4j/documents4j#65]
We are getting the below error when converting the docx file to PDF in server. The sample code is working fine when executed in eclipse in same server. 

com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Code -**
InputStream docxInputStream = new FileInputStream(inputWord);
OutputStream outputStream = new FileOutputStream(outputFile);
IConverter converter = LocalConverter.builder().build();
            converter.convert(docxInputStream).as(DocumentType.DOCX).to(outputStream).as(DocumentType.PDF).execute();
            
converter.shutDown();
outputStream.close();
docxInputStream.close();
----------------------

Can you kindly guide us?
Thanks in advance.

**Comment by raphw** [comment]
Can you open the document in MS Word itself? It normally implies that the document is actually not processable by MS Word.

**Comment by Subash2891** [comment]
Yes, we are able to open the MS word document inside the server.

**Comment by raphw** [comment]
You can try to use the VBS script that is enclosed in the MS Word bridge. It might yield an error code that is more descriptive of the problem.

**Comment by fambrogl** [comment]
Dear all,
I have experienced the same problem.
The code that I'm using to convert the file in pdf is basically the same used by @Subash2891.

My application is build using JDK13 and tested also with JDK14 and the that use the library documents4j V1.1.2

If I run the code in a PC with Windows10 and Office 365 everithing runs smooth, when I try to run the same program on Win7 and Office 2013 I gots the error mentioned on the subject of this thread.

So following your suggestion I have open my *.jar file with WinRAR and I hava copied the VBS scripts that I have found inside the package.

Runing seperately on the command shell the vbs scriptsI have found that the problem happens on the "word_convert.vbs" script. In particular this is the problematic line

**Set wordDocument = wordApplication.Documents.Open(inputFile, False, , False, "dummy-password-to-avoid-lock")**

Using Word2013 the content of the wordDocument variable after this call is empty. After reading various windows documentation pages and attempts I have found that if I modify the line as follow

**Set wordDocument = wordApplication.Documents.Open(inputFile, False, , False)**

everithing works fine on both configuration.

For the moment I can patch by hand my application. 
Could it be possible include a fix for this problem in one of the next releases?

**Comment by raphw** [comment]
It seems like this feature is not working as expected. I have tested this locally and it does not seem to make a difference but I have heard from several sources now that this seems to cause issues. I am therefore considering to remove the feature alltogether.

I released 1.1.3 yesterday and added a possibility to override the conversion script by setting a system property: `-Dcom.documents4j.converter.msoffice.word_convert.vbs=/some/script.vbs`. You can use this in the meantime.

**Comment by SubhashGaikwad** [comment]
Hello Team, Firstly I would like to thanks everyone who has developed such a strong and wonderful java library. I have used this library in my spring boot application and it working fine. used MS word 10 and documnet4j 1.1.5 

I am also facing the same issue "The input file seems to be corrupt" after I deploy war in tomcat 8.5 which is hosted on another windows server where I have MS Word 10 installed. 

public synchronized File convertWordToPdf(File wordFile)
			throws InterruptedException, ExecutionException, IOException {

		File target = new File(wordFile.getParent(), "ouput.pdf");

		
		
		IConverter converter = LocalConverter.builder()
				.baseFolder(new File(wordFile.getParent()))
				.workerPool(20, 25, 2, TimeUnit.SECONDS)
				.processTimeout(30, TimeUnit.SECONDS).build();

		
		
		Future<Boolean> conversion = converter.convert(wordFile)
				.as(DocumentType.DOCX).to(target)
				.as(DocumentType.PDF).prioritizeWith(1000) // optional
				.schedule();

		conversion.get();

		return target;
	}

Please guys help me out with this issue..... Thanks in advance ..........

**Comment by raphw** [comment]
Did you check the Tomcat run configuration? If it's running as a service, you need to take some extra steps that are described on documents4j.com.

**Comment by SubhashGaikwad** [comment]
> Did you check the Tomcat run configuration? If it's running as a service, you need to take some extra steps that are described on documents4j.com.

I am new to the same...so not sure to take the run configuration and what kind of steps I need to take....can please give bit details about this...?

**Comment by SubhashGaikwad** [comment]
> Did you check the Tomcat run configuration? If it's running as a service, you need to take some extra steps that are described on documents4j.com.

I am new to the same...so not sure to take the run configuration and what kind of steps I need to take....can please give bit details about this...then it will great helf to me.

**Comment by raphw** [comment]
Look for 'Running documents4j application as a Windows service' on documents4j.com.

**Comment by DevasishBanerjee** [comment]
Even after using the latest documents4j maven dependency, I am still getting the error in my Tomcat9 server, com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
This works absolutely fine in Eclipse

**Comment by kuopching** [comment]
Hi, I had the same problem. I resolved it with "Ogawa Hack" [1].  Create folder "Desktop" in 
C:\Windows\SysWOW64\config\systemprofile\
and
C:\Windows\System32\config\systemprofile\


1.
https://stackoverflow.com/questions/1006923/automating-office-via-windows-service-on-server-2008

**Comment by webmaster-qiagroup** [comment]
I couldn't resolve the issue even when adding the Desktop folder to systemprofile for 64 bit in sysWOW64.
I wouldn't want to update regedit due to IT restrictions. 
Is there another way?

**Comment by wxnewtouch** [comment]
![image](https://github.com/user-attachments/assets/5468f62c-16b0-49e6-9b3c-ad1af3fd7e55)
wo我在多线程环境下使用了这个报错截图如下
