### ISSUE TITLE
Receive NullPointerException from standalone server in V1.1.0 during start up

### ISSUE THREAD

**Issue by homsai** [documents4j/documents4j#75]
Hi,
Please have a look at this. 
F.Y.I. I've tried '-M'
Downloaded from: https://bintray.com/raphw/maven/documents4j/1.1.0

2019-09-04 13:30:28,635 ERROR [main] c.documents4j.standalone.StandaloneServer - The documents4j server terminated with an unexpected error
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at com.documents4j.builder.ConverterServerBuilder.serviceMode(ConverterServerBuilder.java:228)
	at com.documents4j.standalone.StandaloneServer.asBuilder(StandaloneServer.java:172)
	at com.documents4j.standalone.StandaloneServer.main(StandaloneServer.java:51)

Cheers
Sam

**Comment by raphw** [comment]
There is a copy-pasted null check that I need to fix. Planning to release a corrected version tonight.

**Comment by homsai** [comment]
Hi @raphw,

Thanks for the update of 1.1.1
I cannot download documents4j-server-standalone-1.1.1-shaded.jar from https://bintray.com/raphw/maven/documents4j/1.1.1
Could you please check and re-upload if possible? (It is not shaded version)

Cheers
Sam

**Comment by raphw** [comment]
I can download the jar just ok. How did it not work for you?

**Comment by homsai** [comment]
Hi @raphw,
Thanks for your quick reply. I found it in 'Files' section now. I used to download it from 'Downloads'.
I will close this case.
![image](https://user-images.githubusercontent.com/8316338/65554916-4a73a400-df6e-11e9-887e-076dd62e17d8.png)
Cheers
Sam
