### ISSUE TITLE
com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt

### ISSUE THREAD

**Issue by ekta-vegad** [documents4j/documents4j#79]
We tried to resolve issue by all the solution provided, but still getting this error

com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

2019-10-10 12:23:57,553 ERROR [stderr] (default task-30) 	at java.lang.Thread.run(Thread.java:748)

last time when this error observed, we created "Desktop" folder in syswow64, but in windows 2016 with MS word 2013 this error is still occuring. Please let us know possible solution for this.

**Comment by ekta-vegad** [comment]
is there any command to run same conversion from command prompt? If so , than we can verify from server It's working or not. Which will be helpful.
Or if we can run as a service, than provide us a steps, which will be helpful for us.
Thanks.

**Comment by ekta-vegad** [comment]
Also different behaviour when running from application not working , and when running direct from static java code (public static void main) workring fine.

2019-11-26 11:59:31,208 DEBUG [org.zeroturnaround.exec.WaitForProcess] (WaitForProcess-java.lang.ProcessImpl@4b94833b) java.lang.ProcessImpl@4b94833b stopped with exit code -2

2019-11-26 11:59:31,208 ERROR [stderr] (default task-54) com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt


Please help us to solve this issue.

**Comment by raphw** [comment]
The desktop folder is only required when running documents4j as a service. That it works one way but not the other indicates that you have not created the correct folder for the service user. As I said, I do not have a copy of this Windows version, I am afraid you will have to trial and error.

**Comment by lomoya90** [comment]
@raphw The desktop folder exists , but the error still exists, and the word cannot be converted when running documents4j as a service. How to do ?

**Comment by lomoya90** [comment]
@ekta-vegad Did you solve it ?

**Comment by ekta-vegad** [comment]
After running service with full admin access also on ms word, it worked fine
