### ISSUE TITLE
Conversion failed for an unknown reason

### ISSUE THREAD

**Issue by alhussien-cic** [documents4j/documents4j#81]
Iam trying to convert docx to pdf using RemoteConverter but i get this error:

 ```
com.documents4j.job.RemoteConverter      : The documents4j remote converter has started successfully (URI: http://simple-re.herokuapp.com)
2019-11-11T08:05:32.846702+00:00 heroku[router]: at=info method=POST path="/" host=simple-re.herokuapp.com request_id=3e3cac37-16a9-491b-9a71-ac875d73d3f5 fwd="54.216.171.248" dyno=web.1 connect=1ms service=152ms status=406 bytes=303 protocol=http
2019-11-11T08:05:32.808194+00:00 app[web.1]: 2019-11-11 08:05:32.807  WARN 4 --- [io-35482-exec-6] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]
2019-11-11T08:05:32.893817+00:00 app[web.1]: com.documents4j.throwables.ConverterException: Conversion failed for an unknown reason
2019-11-11T08:05:32.893943+00:00 app[web.1]: 	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:90)
2019-11-11T08:05:32.894000+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-11-11T08:05:32.894025+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-11-11T08:05:32.894114+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748)
```

code:
```
ByteArrayOutputStream bos2 = new ByteArrayOutputStream();
			try {
				InputStream docxInputStream = new ByteArrayInputStream(bos.toByteArray());
				
                        IConverter converter = RemoteConverter.builder()
                                .baseFolder(null)
                                .workerPool(20, 25, 2, TimeUnit.SECONDS)
                                .requestTimeout(10, TimeUnit.SECONDS)
                                .baseUri("http://simple-re.herokuapp.com")
                                .build();
			converter.convert(docxInputStream).as(DocumentType.DOCX).to(bos2).as(DocumentType.PDF).execute();

			} catch (Exception e) {
				e.printStackTrace();
			}

```

**Comment by raphw** [comment]
Does your Heroku Server run Windows and MS Word?

**Comment by alhussien-cic** [comment]
> Does your Heroku Server run Windows and MS Word?

actually i dont know about that, here is my config vars 
![Capture](https://user-images.githubusercontent.com/54809032/68739420-71a33500-05f1-11ea-85f2-eeeb408f3afa.PNG)

and buildpack

![Capture1](https://user-images.githubusercontent.com/54809032/68739450-8384d800-05f1-11ea-8e4d-2c2fdba71488.PNG)

**Comment by alhussien-cic** [comment]
> Does your Heroku Server run Windows and MS Word?

can u please answer my question thanks in advance

**Comment by raphw** [comment]
I deleted your first message, please change your API token, it would give access to your account and it was exposed in your screenshot.

From what I can tell: no, your Heroku server does not run Word, this is however required for documents4j to function.

**Comment by alhussien-cic** [comment]
> I deleted your first message, please change your API token, it would give access to your account and it was exposed in your screenshot.
Thank you for your consideration, but don't worry that's not my main server
> 
> From what I can tell: no, your Heroku server does not run Word, this is however required for documents4j to function.

 I will try to search how to run MS Word on Heroku server, kindly if you know some URLS that's can help me with this issue  please send it to me 
Thank you.
