### ISSUE TITLE
The input file seems to be corrupt

### ISSUE THREAD

**Issue by reboot-new** [documents4j/documents4j#84]
Docx to PDF is faild when I installed springboot as Windows service via nssm。
ERROR 2019-12-07 16:00:44.364 [http-nio-8088-exec-1] org.apache.juli.logging.DirectJDKLog 175 log - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt] with root cause com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159) ~[documents4j-util-all-1.1.1.jar!/:?]
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75) ~[documents4j-util-all-1.1.1.jar!/:?]
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70) ~[documents4j-transformer-api-1.1.1.jar!/:?]
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48) ~[documents4j-util-transformer-process-1.1.1.jar!/:?]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36) ~[documents4j-util-transformer-process-1.1.1.jar!/:?]
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11) ~[documents4j-util-transformer-process-1.1.1.jar!/:?]
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78) ~[documents4j-util-conversion-1.1.1.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

but There was no problem when I started with java -jar aaa.jar.

**Comment by raphw** [comment]
Check documents4j.com which describes a few extra steps necessary if running it as a service.

**Comment by reboot-new** [comment]
> Check documents4j.com which describes a few extra steps necessary if running it as a service.

OK。thanks\
