### ISSUE TITLE
Could not complete conversion

### ISSUE THREAD

**Issue by pietro080394** [documents4j/documents4j#88]
Code:

`Converter converter = LocalConverter.builder()
                        .baseFolder(new File("C:\\tmp"))
                        .workerPool(20, 25, 2, TimeUnit.SECONDS)
                        .processTimeout(5, TimeUnit.SECONDS)
                        .build();
Future<Boolean> conversion = converter
                        .convert(contract).as(DocumentType.MS_WORD)
                        .to(docxFile).as(DocumentType.DOCX)
                        .prioritizeWith(1000)
                        .schedule();
                logger.info("Converted : " + conversion.get());`

Exception:

`java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:205)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
`

I am trying to convert a .doc file into a .docx file but I get the above error

**Comment by pietro080394** [comment]
![Capture](https://user-images.githubusercontent.com/63117244/78385144-b436cf80-75db-11ea-8e82-63c82c728f7e.PNG)

**Comment by raphw** [comment]
Maybe I messed up that last update. Did you try the previous version?

**Comment by raphw** [comment]
Yes, MS Word needs to be installed.
