### ISSUE TITLE
FileSystemInteractionException: Could not access target file

### ISSUE THREAD

**Issue by xuzhu007** [documents4j/documents4j#90]
hi, my documents4j-server-standalone-1.1.2-SNAPSHOT-shaded.jar  service is running on a Windows 10 server, and today an unexpected exception caused the file conversion to fail
errorlog:
2020-04-29 14:00:17,519 INFO  [pool-3-thread-6] c.d.c.msoffice.MicrosoftWordBridge - Requested conversion from C:\Users\ADMINI~1\AppData\Local\Temp\2\1588138759505-0\f35baf61-16ce-4c80-ac22-ae2d1b81fa81\temp431 (application/vnd.com.documents4j.any-msword) to C:\Users\ADMINI~1\AppData\Local\Temp\2\1588138759505-0\f35baf61-16ce-4c80-ac22-ae2d1b81fa81\temp432 (application/pdf)
2020-04-29 14:00:18,199 WARN  [pool-3-thread-1] c.d.job.FileSourceFromInputStreamSource - Could not delete temporary file C:\Users\ADMINI~1\AppData\Local\Temp\2\1588138759505-0\f35baf61-16ce-4c80-ac22-ae2d1b81fa81\temp421
2020-04-29 14:00:18,209 INFO  [pool-3-thread-1] c.d.w.e.AsynchronousConversionResponse - Sending exceptional response for org.glassfish.jersey.server.ServerRuntime$AsyncResponder@4fa0b694
com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by xuzhu007** [comment]
I haven't found the cause of the problem, please help me find the cause of the problem, thank you

**Comment by raphw** [comment]
It seems like your process cannot access the file system. Did you try setting an explicit base folder? Check the server arguments for a summary of your configuration options.

**Comment by xuzhu007** [comment]
thanks.The problem has been resolved because the file uploaded by the user was encrypted, resulting in a parsing failure
