### ISSUE TITLE
java.lang.IllegalStateException: class com.documents4j.conversion.msoffice.MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor

### ISSUE THREAD

**Issue by gionnyFuego** [documents4j/documents4j#93]
When I try to convert doc to html using LocalConverter I got this

java.util.concurrent.TimeoutException: Timed out waiting for java.lang.ProcessImpl@4e5ead5a to finish, timeout: 15000 milliseconds, executed command [cmd, /S, /C, ""C:\Users\Administrator\tmp\word_start843151969.vbs""] in directory C:\Users\Administrator\tmp, output was 0 bytes:

        at org.zeroturnaround.exec.ProcessExecutor.newTimeoutException(ProcessExecutor.java:1180)
        at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1111)
        at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:906)
        at com.documents4j.conversion.AbstractExternalConverter.runNoArgumentScript(AbstractExternalConverter.java:72)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.runNoArgumentScript(AbstractMicrosoftOfficeBridge.java:51)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.tryStart(AbstractMicrosoftOfficeBridge.java:34)
        at com.documents4j.conversion.msoffice.MicrosoftWordBridge.startUp(MicrosoftWordBridge.java:46)
        at com.documents4j.conversion.msoffice.MicrosoftWordBridge.<init>(MicrosoftWordBridge.java:41)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:30)
        at com.documents4j.conversion.ExternalConverterDiscovery.makeAll(ExternalConverterDiscovery.java:42)
        at com.documents4j.conversion.ExternalConverterDiscovery.loadConfiguration(ExternalConverterDiscovery.java:85)
        at com.documents4j.conversion.DefaultConversionManager.<init>(DefaultConversionManager.java:22)
        at com.documents4j.job.LocalConverter.makeConversionManager(LocalConverter.java:79)
        at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:51)
        at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:186)
        at cuga.fuck.gugl.conv.Convert2ZippedHTML.doPost(Convert2ZippedHTML.java:158)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1201)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: class com.documents4j.conversion.msoffice.MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor
        at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:32)

**Comment by swk-lb** [comment]
Today I experienced the same issue. After the crash a word process was still running. I started the conversion again and everything worked fine. If I kill the process, the conversion crashes with the same exception.

**Comment by raphw** [comment]
It's hard to tell what the problem is given the little contextual information. If the converter crashes, it's best to restart the server.

documents4j offers load balancing that allows for restarts of a failed node.
