### ISSUE TITLE
concurrent conversion problems (already posted)

### ISSUE THREAD

**Issue by gionnyFuego** [documents4j/documents4j#95]
Hi, I'm using LocalConverter in a Servlet java (on tomcat)
When I access with one client no problems.
When I access it with 12 clients, LocalConverter hangs and goes in timeout.
What's the problem?

Sorry for my poor english.

**Comment by raphw** [comment]
You need to run the converter as a singleton instance throughout the server. You cannot run multiple instances of it.

**Comment by gionnydeep75** [comment]
but in this way is synchronous. No multithreads

**Comment by raphw** [comment]
Yes, this is in the nature of using MS Word. documents4j already enables some concurrency, but it needs to be controlled to not crash the converter.

**Comment by gionnydeep75** [comment]
But when conversion fails for some strange reason (probably a thread locks) documets4j-server hangs throws this:
 
2020-05-18 10:24:56,965 ERROR [main] c.d.c.msoffice.MicrosoftWordBridge - Thread responsible for running script timed out: c:\test\word_start295692647.vbs
java.util.concurrent.TimeoutException: Timed out waiting for java.lang.ProcessImpl@27216cd to finish, timeout: 5000 milliseconds, executed command [cmd, /S, /C, ""c:\test\word_start295692647.vbs""] in directory c:\test, output was 0 bytes:

        at org.zeroturnaround.exec.ProcessExecutor.newTimeoutException(ProcessExecutor.java:1180)
        at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1111)
        at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:906)
        at com.documents4j.conversion.AbstractExternalConverter.runNoArgumentScript(AbstractExternalConverter.java:72)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.runNoArgumentScript(AbstractMicrosoftOfficeBridge.java:51)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.tryStart(AbstractMicrosoftOfficeBridge.java:34)
        at com.documents4j.conversion.msoffice.MicrosoftWordBridge.startUp(MicrosoftWordBridge.java:46)
        at com.documents4j.conversion.msoffice.MicrosoftWordBridge.<init>(MicrosoftWordBridge.java:41)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:30)
        at com.documents4j.conversion.ExternalConverterDiscovery.makeAll(ExternalConverterDiscovery.java:42)
        at com.documents4j.conversion.ExternalConverterDiscovery.loadConfiguration(ExternalConverterDiscovery.java:85)
        at com.documents4j.conversion.DefaultConversionManager.<init>(DefaultConversionManager.java:22)
        at com.documents4j.job.LocalConverter.makeConversionManager(LocalConverter.java:79)
        at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:51)
        at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:186)
        at com.documents4j.ws.application.StandaloneWebConverterConfiguration.onStartup(StandaloneWebConverterConfiguration.java:66)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:707)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:330)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:398)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:293)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:269)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:267)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:93)
        at com.documents4j.builder.ConverterServerBuilder.build(ConverterServerBuilder.java:253)
        at com.documents4j.standalone.StandaloneServer.main(StandaloneServer.java:52)
2020-05-18 10:24:57,043 ERROR [main] c.documents4j.standalone.StandaloneServer - The documents4j server terminated with an unexpected error
java.lang.IllegalStateException: class com.documents4j.conversion.msoffice.MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor
        at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:32)
        at com.documents4j.conversion.ExternalConverterDiscovery.makeAll(ExternalConverterDiscovery.java:42)
        at com.documents4j.conversion.ExternalConverterDiscovery.loadConfiguration(ExternalConverterDiscovery.java:85)
        at com.documents4j.conversion.DefaultConversionManager.<init>(DefaultConversionManager.java:22)
        at com.documents4j.job.LocalConverter.makeConversionManager(LocalConverter.java:79)
        at com.documents4j.job.LocalConverter.<init>(LocalConverter.java:51)
        at com.documents4j.job.LocalConverter$Builder.build(LocalConverter.java:186)
        at com.documents4j.ws.application.StandaloneWebConverterConfiguration.onStartup(StandaloneWebConverterConfiguration.java:66)
        at org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:707)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:330)
        at org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:398)
        at org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:293)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:269)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:267)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory.createHttpServer(GrizzlyHttpServerFactory.java:93)
        at com.documents4j.builder.ConverterServerBuilder.build(ConverterServerBuilder.java:253)
        at com.documents4j.standalone.StandaloneServer.main(StandaloneServer.java:52)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.documents4j.conversion.ExternalConverterDiscovery.make(ExternalConverterDiscovery.java:30)
        ... 16 common frames omitted
Caused by: com.documents4j.throwables.ConverterAccessException: Thread responsible for running script timed out: c:\test\word_start295692647.vbs
        at com.documents4j.conversion.AbstractExternalConverter.runNoArgumentScript(AbstractExternalConverter.java:84)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.runNoArgumentScript(AbstractMicrosoftOfficeBridge.java:51)
        at com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge.tryStart(AbstractMicrosoftOfficeBridge.java:34)
        at com.documents4j.conversion.msoffice.MicrosoftWordBridge.startUp(MicrosoftWordBridge.java:46)
        at com.documents4j.conversion.msoffice.MicrosoftWordBridge.<init>(MicrosoftWordBridge.java:41)
        ... 21 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Timed out waiting for java.lang.ProcessImpl@27216cd to finish, timeout: 5000 milliseconds, executed command [cmd, /S, /C, ""c:\test\word_start295692647.vbs""] in directory c:\test, output was 0 bytes:

        at org.zeroturnaround.exec.ProcessExecutor.newTimeoutException(ProcessExecutor.java:1180)
        at org.zeroturnaround.exec.ProcessExecutor.waitFor(ProcessExecutor.java:1111)
        at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:906)
        at com.documents4j.conversion.AbstractExternalConverter.runNoArgumentScript(AbstractExternalConverter.java:72)
        ... 25 common frames omitted
Error: class com.documents4j.conversion.msoffice.MicrosoftWordBridge could not be created by a (File, long, TimeUnit) constructor
Use option -? to display a list of legal commands.
Exception in thread "Shutdown hook: com.documents4j.job.LocalConverter" java.lang.NullPointerException
        at com.documents4j.job.LocalConverter.shutDown(LocalConverter.java:100)
        at com.documents4j.job.ConverterAdapter$ConverterShutdownHook.run(ConverterAdapter.java:146)

C:\documents4j-master\documents4j-server-standalone\target>

**Comment by raphw** [comment]
It's because the Word background process trips, Word is not build for throwing thousands of requests at it, this is why documents4j needs to be a gate keeper.
